! THIS VERSION: 22/03/2021 AT 09:30:00 GMT.

!- G A L A H A D  -  M K L  P A R A D I S O  I N T E R F A C E   M O D U L E S -

MODULE MKL_PARDISO_PRIVATE
  TYPE MKL_PARDISO_HANDLE
    INTEGER( KIND = SELECTED_INT_KIND( 18 ) ) DUMMY
  END TYPE
  INTEGER, PARAMETER :: PARDISO_OOC_FILE_NAME = 1
END MODULE MKL_PARDISO_PRIVATE

MODULE MKL_PARDISO
  USE MKL_PARDISO_PRIVATE

  INTERFACE MKL_PARDISO_SOLVE
    SUBROUTINE PARDISO_S( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,        &
                          PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
      USE MKL_PARDISO_PRIVATE
      INTEGER, PARAMETER :: sp = KIND( 1.0 )
      TYPE( MKL_PARDISO_HANDLE ), INTENT( INOUT ) :: PT( * )
      INTEGER, INTENT( IN ) :: MAXFCT
      INTEGER, INTENT( IN ) :: MNUM
      INTEGER, INTENT( IN ) :: MTYPE
      INTEGER, INTENT( IN ) :: PHASE
      INTEGER, INTENT( IN ) :: N
      INTEGER, INTENT( IN ) :: IA( * )
      INTEGER, INTENT( IN ) :: JA( * )
      INTEGER, INTENT( INOUT ) :: PERM( * )
      INTEGER, INTENT( IN ) :: NRHS
      INTEGER, INTENT( INOUT ) :: IPARM( * )
      INTEGER, INTENT( IN ) :: MSGLVL
      INTEGER, INTENT( OUT ) :: ERROR
      REAL( KIND = sp ), INTENT( IN ) :: A( * )
      REAL( KIND = sp ), INTENT( INOUT ) :: B( * )
      REAL( KIND = sp ), INTENT( OUT ) :: X( * )
    END SUBROUTINE PARDISO_S

    SUBROUTINE PARDISO_D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,        &
                          PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
      USE MKL_PARDISO_PRIVATE
      INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
      TYPE( MKL_PARDISO_HANDLE ), INTENT( INOUT ) :: PT( * )
      INTEGER, INTENT( IN ) :: MAXFCT
      INTEGER, INTENT( IN ) :: MNUM
      INTEGER, INTENT( IN ) :: MTYPE
      INTEGER, INTENT( IN ) :: PHASE
      INTEGER, INTENT( IN ) :: N
      INTEGER, INTENT( IN ) :: IA( * )
      INTEGER, INTENT( IN ) :: JA( * )
      INTEGER, INTENT( INOUT ) :: PERM( * )
      INTEGER, INTENT( IN ) :: NRHS
      INTEGER, INTENT( INOUT ) :: IPARM( * )
      INTEGER, INTENT( IN ) :: MSGLVL
      INTEGER, INTENT( OUT ) :: ERROR
      REAL( KIND = dp ), INTENT( IN ) :: A( * )
      REAL( KIND = dp ), INTENT( INOUT ) :: B( * )
      REAL( KIND = dp ), INTENT( OUT ) :: X( * )
    END SUBROUTINE PARDISO_D

    SUBROUTINE PARDISO_S_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,     &
                             PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
      USE MKL_PARDISO_PRIVATE
      INTEGER, PARAMETER :: sp = KIND( 1.0 )
      TYPE( MKL_PARDISO_HANDLE ), INTENT( INOUT ) :: PT( * )
      INTEGER, INTENT( IN ) :: MAXFCT
      INTEGER, INTENT( IN ) :: MNUM
      INTEGER, INTENT( IN ) :: MTYPE
      INTEGER, INTENT( IN ) :: PHASE
      INTEGER, INTENT( IN ) :: N
      INTEGER, INTENT( IN ) :: IA( * )
      INTEGER, INTENT( IN ) :: JA( * )
      INTEGER, INTENT( INOUT ) :: PERM( * )
      INTEGER, INTENT( IN ) :: NRHS
      INTEGER, INTENT( INOUT ) :: IPARM( * )
      INTEGER, INTENT( IN ) :: MSGLVL
      INTEGER, INTENT( OUT ) :: ERROR
      REAL( KIND = sp ), INTENT( IN ) :: A( * )
      REAL( KIND = sp ), INTENT( INOUT ) :: B( N, * )
      REAL( KIND = sp ), INTENT( OUT ) :: X( N, * )
    END SUBROUTINE PARDISO_S_2D

    SUBROUTINE PARDISO_D_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,     &
                             PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
      USE MKL_PARDISO_PRIVATE
      INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
      TYPE( MKL_PARDISO_HANDLE ), INTENT( INOUT ) :: PT( * )
      INTEGER, INTENT( IN ) :: MAXFCT
      INTEGER, INTENT( IN ) :: MNUM
      INTEGER, INTENT( IN ) :: MTYPE
      INTEGER, INTENT( IN ) :: PHASE
      INTEGER, INTENT( IN ) :: N
      INTEGER, INTENT( IN ) :: IA( * )
      INTEGER, INTENT( IN ) :: JA( * )
      INTEGER, INTENT( INOUT ) :: PERM( * )
      INTEGER, INTENT( IN ) :: NRHS
      INTEGER, INTENT( INOUT ) :: IPARM( * )
      INTEGER, INTENT( IN ) :: MSGLVL
      INTEGER, INTENT( OUT ) :: ERROR
      REAL( KIND = dp ), INTENT( IN ) :: A( * )
      REAL( KIND = dp ), INTENT( INOUT ) :: B( N, * )
      REAL( KIND = dp ), INTENT( OUT ) :: X( N, * )
    END SUBROUTINE PARDISO_D_2D
  END INTERFACE MKL_PARDISO_SOLVE

END MODULE MKL_PARDISO

