using GALAHAD
using Quadmath

# Structures for arc
Ref{arc_control_type{Float32}}()
Ref{arc_control_type{Float64}}()
Ref{arc_control_type{Float128}}()
Ref{arc_time_type{Float32}}()
Ref{arc_time_type{Float64}}()
Ref{arc_time_type{Float128}}()
Ref{arc_inform_type{Float32}}()
Ref{arc_inform_type{Float64}}()
Ref{arc_inform_type{Float128}}()

# Structures for bgo
Ref{bgo_control_type{Float32}}()
Ref{bgo_control_type{Float64}}()
Ref{bgo_control_type{Float128}}()
Ref{bgo_time_type{Float32}}()
Ref{bgo_time_type{Float64}}()
Ref{bgo_time_type{Float128}}()
Ref{bgo_inform_type{Float32}}()
Ref{bgo_inform_type{Float64}}()
Ref{bgo_inform_type{Float128}}()

# Structures for blls
Ref{blls_control_type{Float32}}()
Ref{blls_control_type{Float64}}()
Ref{blls_control_type{Float128}}()
Ref{blls_time_type{Float32}}()
Ref{blls_time_type{Float64}}()
Ref{blls_time_type{Float128}}()
Ref{blls_inform_type{Float32}}()
Ref{blls_inform_type{Float64}}()
Ref{blls_inform_type{Float128}}()

# Structures for bllsb
Ref{bllsb_control_type{Float32}}()
Ref{bllsb_control_type{Float64}}()
Ref{bllsb_control_type{Float128}}()
Ref{bllsb_time_type{Float32}}()
Ref{bllsb_time_type{Float64}}()
Ref{bllsb_time_type{Float128}}()
Ref{bllsb_inform_type{Float32}}()
Ref{bllsb_inform_type{Float64}}()
Ref{bllsb_inform_type{Float128}}()

# Structures for bnls
Ref{bnls_subproblem_control_type{Float32}}()
Ref{bnls_subproblem_control_type{Float64}}()
Ref{bnls_subproblem_control_type{Float128}}()
Ref{bnls_control_type{Float32}}()
Ref{bnls_control_type{Float64}}()
Ref{bnls_control_type{Float128}}()
Ref{bnls_time_type{Float32}}()
Ref{bnls_time_type{Float64}}()
Ref{bnls_time_type{Float128}}()
Ref{bnls_subproblem_inform_type{Float32}}()
Ref{bnls_subproblem_inform_type{Float64}}()
Ref{bnls_subproblem_inform_type{Float128}}()
Ref{bnls_inform_type{Float32}}()
Ref{bnls_inform_type{Float64}}()
Ref{bnls_inform_type{Float128}}()

# Structures for bqp
Ref{bqp_control_type{Float32}}()
Ref{bqp_control_type{Float64}}()
Ref{bqp_control_type{Float128}}()
Ref{bqp_time_type}()
Ref{bqp_inform_type{Float32}}()
Ref{bqp_inform_type{Float64}}()
Ref{bqp_inform_type{Float128}}()

# Structures for bqpb
Ref{bqpb_control_type{Float32}}()
Ref{bqpb_control_type{Float64}}()
Ref{bqpb_control_type{Float128}}()
Ref{bqpb_time_type{Float32}}()
Ref{bqpb_time_type{Float64}}()
Ref{bqpb_time_type{Float128}}()
Ref{bqpb_inform_type{Float32}}()
Ref{bqpb_inform_type{Float64}}()
Ref{bqpb_inform_type{Float128}}()

# Structures for bsc
Ref{bsc_control_type}()
Ref{bsc_inform_type{Float32}}()
Ref{bsc_inform_type{Float64}}()
Ref{bsc_inform_type{Float128}}()

# Structures for ccqp
Ref{ccqp_control_type{Float32}}()
Ref{ccqp_control_type{Float64}}()
Ref{ccqp_control_type{Float128}}()
Ref{ccqp_time_type{Float32}}()
Ref{ccqp_time_type{Float64}}()
Ref{ccqp_time_type{Float128}}()
Ref{ccqp_inform_type{Float32}}()
Ref{ccqp_inform_type{Float64}}()
Ref{ccqp_inform_type{Float128}}()

# Structures for clls
Ref{clls_control_type{Float32}}()
Ref{clls_control_type{Float64}}()
Ref{clls_control_type{Float128}}()
Ref{clls_time_type{Float32}}()
Ref{clls_time_type{Float64}}()
Ref{clls_time_type{Float128}}()
Ref{clls_inform_type{Float32}}()
Ref{clls_inform_type{Float64}}()
Ref{clls_inform_type{Float128}}()

# Structures for convert
Ref{convert_control_type}()
Ref{convert_time_type{Float32}}()
Ref{convert_time_type{Float64}}()
Ref{convert_time_type{Float128}}()
Ref{convert_inform_type{Float32}}()
Ref{convert_inform_type{Float64}}()
Ref{convert_inform_type{Float128}}()

# Structures for cqp
Ref{cqp_control_type{Float32}}()
Ref{cqp_control_type{Float64}}()
Ref{cqp_control_type{Float128}}()
Ref{cqp_time_type{Float32}}()
Ref{cqp_time_type{Float64}}()
Ref{cqp_time_type{Float128}}()
Ref{cqp_inform_type{Float32}}()
Ref{cqp_inform_type{Float64}}()
Ref{cqp_inform_type{Float128}}()

# Structures for cro
Ref{cro_control_type{Float32}}()
Ref{cro_control_type{Float64}}()
Ref{cro_control_type{Float128}}()
Ref{cro_time_type{Float32}}()
Ref{cro_time_type{Float64}}()
Ref{cro_time_type{Float128}}()
Ref{cro_inform_type{Float32}}()
Ref{cro_inform_type{Float64}}()
Ref{cro_inform_type{Float128}}()

# Structures for dgo
Ref{dgo_control_type{Float32}}()
Ref{dgo_control_type{Float64}}()
Ref{dgo_control_type{Float128}}()
Ref{dgo_time_type{Float32}}()
Ref{dgo_time_type{Float64}}()
Ref{dgo_time_type{Float128}}()
Ref{dgo_inform_type{Float32}}()
Ref{dgo_inform_type{Float64}}()
Ref{dgo_inform_type{Float128}}()

# Structures for dps
Ref{dps_control_type{Float32}}()
Ref{dps_control_type{Float64}}()
Ref{dps_control_type{Float128}}()
Ref{dps_time_type{Float32}}()
Ref{dps_time_type{Float64}}()
Ref{dps_time_type{Float128}}()
Ref{dps_inform_type{Float32}}()
Ref{dps_inform_type{Float64}}()
Ref{dps_inform_type{Float128}}()

# Structures for dqp
Ref{dqp_control_type{Float32}}()
Ref{dqp_control_type{Float64}}()
Ref{dqp_control_type{Float128}}()
Ref{dqp_time_type{Float32}}()
Ref{dqp_time_type{Float64}}()
Ref{dqp_time_type{Float128}}()
Ref{dqp_inform_type{Float32}}()
Ref{dqp_inform_type{Float64}}()
Ref{dqp_inform_type{Float128}}()

# Structures for eqp
Ref{eqp_control_type{Float32}}()
Ref{eqp_control_type{Float64}}()
Ref{eqp_control_type{Float128}}()
Ref{eqp_time_type{Float32}}()
Ref{eqp_time_type{Float64}}()
Ref{eqp_time_type{Float128}}()
Ref{eqp_inform_type{Float32}}()
Ref{eqp_inform_type{Float64}}()
Ref{eqp_inform_type{Float128}}()

# Structures for fdc
Ref{fdc_control_type{Float32}}()
Ref{fdc_control_type{Float64}}()
Ref{fdc_control_type{Float128}}()
Ref{fdc_time_type{Float32}}()
Ref{fdc_time_type{Float64}}()
Ref{fdc_time_type{Float128}}()
Ref{fdc_inform_type{Float32}}()
Ref{fdc_inform_type{Float64}}()
Ref{fdc_inform_type{Float128}}()

# Structures for fit
Ref{fit_control_type}()
Ref{fit_inform_type}()

# Structures for glrt
Ref{glrt_control_type{Float32}}()
Ref{glrt_control_type{Float64}}()
Ref{glrt_control_type{Float128}}()
Ref{glrt_inform_type{Float32}}()
Ref{glrt_inform_type{Float64}}()
Ref{glrt_inform_type{Float128}}()

# Structures for gls
Ref{gls_control_type{Float32}}()
Ref{gls_control_type{Float64}}()
Ref{gls_control_type{Float128}}()
Ref{gls_ainfo_type{Float32}}()
Ref{gls_ainfo_type{Float64}}()
Ref{gls_ainfo_type{Float128}}()
Ref{gls_finfo_type{Float32}}()
Ref{gls_finfo_type{Float64}}()
Ref{gls_finfo_type{Float128}}()
Ref{gls_sinfo_type}()

# Structures for gltr
Ref{gltr_control_type{Float32}}()
Ref{gltr_control_type{Float64}}()
Ref{gltr_control_type{Float128}}()
Ref{gltr_inform_type{Float32}}()
Ref{gltr_inform_type{Float64}}()
Ref{gltr_inform_type{Float128}}()

# Structures for hash
Ref{hash_control_type}()
Ref{hash_inform_type}()

# Structures for hsl
Ref{ma48_control{Float32}}()
Ref{ma48_control{Float64}}()
Ref{ma48_control{Float128}}()
Ref{ma48_ainfo{Float32}}()
Ref{ma48_ainfo{Float64}}()
Ref{ma48_ainfo{Float128}}()
Ref{ma48_finfo{Float32}}()
Ref{ma48_finfo{Float64}}()
Ref{ma48_finfo{Float128}}()
Ref{ma48_sinfo}()
Ref{ma57_control{Float32}}()
Ref{ma57_control{Float64}}()
Ref{ma57_control{Float128}}()
Ref{ma57_ainfo{Float32}}()
Ref{ma57_ainfo{Float64}}()
Ref{ma57_ainfo{Float128}}()
Ref{ma57_finfo{Float32}}()
Ref{ma57_finfo{Float64}}()
Ref{ma57_finfo{Float128}}()
Ref{ma57_sinfo{Float32}}()
Ref{ma57_sinfo{Float64}}()
Ref{ma57_sinfo{Float128}}()
Ref{ma77_control{Float32}}()
Ref{ma77_control{Float64}}()
Ref{ma77_control{Float128}}()
Ref{ma77_info{Float32}}()
Ref{ma77_info{Float64}}()
Ref{ma77_info{Float128}}()
Ref{ma86_control{Float32}}()
Ref{ma86_control{Float64}}()
Ref{ma86_control{Float128}}()
Ref{ma86_info{Float32}}()
Ref{ma86_info{Float64}}()
Ref{ma86_info{Float128}}()
Ref{ma87_control{Float32}}()
Ref{ma87_control{Float64}}()
Ref{ma87_control{Float128}}()
Ref{ma87_info{Float32}}()
Ref{ma87_info{Float64}}()
Ref{ma87_info{Float128}}()
Ref{ma97_control{Float32}}()
Ref{ma97_control{Float64}}()
Ref{ma97_control{Float128}}()
Ref{ma97_info{Float32}}()
Ref{ma97_info{Float64}}()
Ref{ma97_info{Float128}}()
Ref{mc64_control}()
Ref{mc64_info}()
Ref{mc68_control}()
Ref{mc68_info}()
Ref{mi20_control{Float32}}()
Ref{mi20_control{Float64}}()
Ref{mi20_control{Float128}}()
Ref{mi20_solve_control{Float32}}()
Ref{mi20_solve_control{Float64}}()
Ref{mi20_solve_control{Float128}}()
Ref{mi20_info{Float32}}()
Ref{mi20_info{Float64}}()
Ref{mi20_info{Float128}}()
Ref{mi28_control{Float32}}()
Ref{mi28_control{Float64}}()
Ref{mi28_control{Float128}}()
Ref{mi28_info{Float32}}()
Ref{mi28_info{Float64}}()
Ref{mi28_info{Float128}}()

# Structures for ir
Ref{ir_control_type{Float32}}()
Ref{ir_control_type{Float64}}()
Ref{ir_control_type{Float128}}()
Ref{ir_inform_type{Float32}}()
Ref{ir_inform_type{Float64}}()
Ref{ir_inform_type{Float128}}()

# Structures for l2rt
Ref{l2rt_control_type{Float32}}()
Ref{l2rt_control_type{Float64}}()
Ref{l2rt_control_type{Float128}}()
Ref{l2rt_inform_type{Float32}}()
Ref{l2rt_inform_type{Float64}}()
Ref{l2rt_inform_type{Float128}}()

# Structures for lhs
Ref{lhs_control_type}()
Ref{lhs_inform_type}()

# Structures for llsr
Ref{llsr_control_type{Float32}}()
Ref{llsr_control_type{Float64}}()
Ref{llsr_control_type{Float128}}()
Ref{llsr_time_type{Float32}}()
Ref{llsr_time_type{Float64}}()
Ref{llsr_time_type{Float128}}()
Ref{llsr_history_type{Float32}}()
Ref{llsr_history_type{Float64}}()
Ref{llsr_history_type{Float128}}()
Ref{llsr_inform_type{Float32}}()
Ref{llsr_inform_type{Float64}}()
Ref{llsr_inform_type{Float128}}()

# Structures for llst
Ref{llst_control_type{Float32}}()
Ref{llst_control_type{Float64}}()
Ref{llst_control_type{Float128}}()
Ref{llst_time_type{Float32}}()
Ref{llst_time_type{Float64}}()
Ref{llst_time_type{Float128}}()
Ref{llst_history_type{Float32}}()
Ref{llst_history_type{Float64}}()
Ref{llst_history_type{Float128}}()
Ref{llst_inform_type{Float32}}()
Ref{llst_inform_type{Float64}}()
Ref{llst_inform_type{Float128}}()

# Structures for lms
Ref{lms_control_type}()
Ref{lms_time_type{Float32}}()
Ref{lms_time_type{Float64}}()
Ref{lms_time_type{Float128}}()
Ref{lms_inform_type{Float32}}()
Ref{lms_inform_type{Float64}}()
Ref{lms_inform_type{Float128}}()

# Structures for lpa
Ref{lpa_control_type{Float32}}()
Ref{lpa_control_type{Float64}}()
Ref{lpa_control_type{Float128}}()
Ref{lpa_time_type{Float32}}()
Ref{lpa_time_type{Float64}}()
Ref{lpa_time_type{Float128}}()
Ref{lpa_inform_type{Float32}}()
Ref{lpa_inform_type{Float64}}()
Ref{lpa_inform_type{Float128}}()

# Structures for lpb
Ref{lpb_control_type{Float32}}()
Ref{lpb_control_type{Float64}}()
Ref{lpb_control_type{Float128}}()
Ref{lpb_time_type{Float32}}()
Ref{lpb_time_type{Float64}}()
Ref{lpb_time_type{Float128}}()
Ref{lpb_inform_type{Float32}}()
Ref{lpb_inform_type{Float64}}()
Ref{lpb_inform_type{Float128}}()

# Structures for lsqp
Ref{lsqp_control_type{Float32}}()
Ref{lsqp_control_type{Float64}}()
Ref{lsqp_control_type{Float128}}()
Ref{lsqp_time_type{Float32}}()
Ref{lsqp_time_type{Float64}}()
Ref{lsqp_time_type{Float128}}()
Ref{lsqp_inform_type{Float32}}()
Ref{lsqp_inform_type{Float64}}()
Ref{lsqp_inform_type{Float128}}()

# Structures for lsrt
Ref{lsrt_control_type{Float32}}()
Ref{lsrt_control_type{Float64}}()
Ref{lsrt_control_type{Float128}}()
Ref{lsrt_inform_type{Float32}}()
Ref{lsrt_inform_type{Float64}}()
Ref{lsrt_inform_type{Float128}}()

# Structures for lstr
Ref{lstr_control_type{Float32}}()
Ref{lstr_control_type{Float64}}()
Ref{lstr_control_type{Float128}}()
Ref{lstr_inform_type{Float32}}()
Ref{lstr_inform_type{Float64}}()
Ref{lstr_inform_type{Float128}}()

# Structures for nls
Ref{nls_subproblem_control_type{Float32}}()
Ref{nls_subproblem_control_type{Float64}}()
Ref{nls_subproblem_control_type{Float128}}()
Ref{nls_control_type{Float32}}()
Ref{nls_control_type{Float64}}()
Ref{nls_control_type{Float128}}()
Ref{nls_time_type{Float32}}()
Ref{nls_time_type{Float64}}()
Ref{nls_time_type{Float128}}()
Ref{nls_subproblem_inform_type{Float32}}()
Ref{nls_subproblem_inform_type{Float64}}()
Ref{nls_subproblem_inform_type{Float128}}()
Ref{nls_inform_type{Float32}}()
Ref{nls_inform_type{Float64}}()
Ref{nls_inform_type{Float128}}()

# Structures for presolve
Ref{presolve_control_type{Float32}}()
Ref{presolve_control_type{Float64}}()
Ref{presolve_control_type{Float128}}()
Ref{presolve_inform_type}()

# Structures for psls
Ref{psls_control_type{Float32}}()
Ref{psls_control_type{Float64}}()
Ref{psls_control_type{Float128}}()
Ref{psls_time_type{Float32}}()
Ref{psls_time_type{Float64}}()
Ref{psls_time_type{Float128}}()
Ref{psls_inform_type{Float32}}()
Ref{psls_inform_type{Float64}}()
Ref{psls_inform_type{Float128}}()

# Structures for qpa
Ref{qpa_control_type{Float32}}()
Ref{qpa_control_type{Float64}}()
Ref{qpa_control_type{Float128}}()
Ref{qpa_time_type{Float32}}()
Ref{qpa_time_type{Float64}}()
Ref{qpa_time_type{Float128}}()
Ref{qpa_inform_type{Float32}}()
Ref{qpa_inform_type{Float64}}()
Ref{qpa_inform_type{Float128}}()

# Structures for qpb
Ref{qpb_control_type{Float32}}()
Ref{qpb_control_type{Float64}}()
Ref{qpb_control_type{Float128}}()
Ref{qpb_time_type{Float32}}()
Ref{qpb_time_type{Float64}}()
Ref{qpb_time_type{Float128}}()
Ref{qpb_inform_type{Float32}}()
Ref{qpb_inform_type{Float64}}()
Ref{qpb_inform_type{Float128}}()

# Structures for roots
Ref{roots_control_type{Float32}}()
Ref{roots_control_type{Float64}}()
Ref{roots_control_type{Float128}}()
Ref{roots_inform_type}()

# Structures for rpd
Ref{rpd_control_type}()
Ref{rpd_inform_type}()

# Structures for rqs
Ref{rqs_control_type{Float32}}()
Ref{rqs_control_type{Float64}}()
Ref{rqs_control_type{Float128}}()
Ref{rqs_time_type{Float32}}()
Ref{rqs_time_type{Float64}}()
Ref{rqs_time_type{Float128}}()
Ref{rqs_history_type{Float32}}()
Ref{rqs_history_type{Float64}}()
Ref{rqs_history_type{Float128}}()
Ref{rqs_inform_type{Float32}}()
Ref{rqs_inform_type{Float64}}()
Ref{rqs_inform_type{Float128}}()

# Structures for sbls
Ref{sbls_control_type{Float32}}()
Ref{sbls_control_type{Float64}}()
Ref{sbls_control_type{Float128}}()
Ref{sbls_time_type{Float32}}()
Ref{sbls_time_type{Float64}}()
Ref{sbls_time_type{Float128}}()
Ref{sbls_inform_type{Float32}}()
Ref{sbls_inform_type{Float64}}()
Ref{sbls_inform_type{Float128}}()

# Structures for scu
Ref{scu_control_type}()
Ref{scu_inform_type}()

# Structures for sec
Ref{sec_control_type{Float32}}()
Ref{sec_control_type{Float64}}()
Ref{sec_control_type{Float128}}()
Ref{sec_inform_type}()

# Structures for sha
Ref{sha_control_type}()
Ref{sha_inform_type{Float32}}()
Ref{sha_inform_type{Float64}}()
Ref{sha_inform_type{Float128}}()

# Structures for sils
Ref{sils_control_type{Float32}}()
Ref{sils_control_type{Float64}}()
Ref{sils_control_type{Float128}}()
Ref{sils_ainfo_type{Float32}}()
Ref{sils_ainfo_type{Float64}}()
Ref{sils_ainfo_type{Float128}}()
Ref{sils_finfo_type{Float32}}()
Ref{sils_finfo_type{Float64}}()
Ref{sils_finfo_type{Float128}}()
Ref{sils_sinfo_type{Float32}}()
Ref{sils_sinfo_type{Float64}}()
Ref{sils_sinfo_type{Float128}}()

# Structures for slls
Ref{slls_control_type{Float32}}()
Ref{slls_control_type{Float64}}()
Ref{slls_control_type{Float128}}()
Ref{slls_time_type}()
Ref{slls_inform_type{Float32}}()
Ref{slls_inform_type{Float64}}()
Ref{slls_inform_type{Float128}}()

# Structures for sls
Ref{sls_control_type{Float32}}()
Ref{sls_control_type{Float64}}()
Ref{sls_control_type{Float128}}()
Ref{sls_time_type{Float32}}()
Ref{sls_time_type{Float64}}()
Ref{sls_time_type{Float128}}()
Ref{sls_inform_type{Float32}}()
Ref{sls_inform_type{Float64}}()
Ref{sls_inform_type{Float128}}()

# Structures for ssids
Ref{spral_ssids_options{Float32}}()
Ref{spral_ssids_options{Float64}}()
Ref{spral_ssids_options{Float128}}()
Ref{spral_ssids_inform}()

# Structures for trb
Ref{trb_control_type{Float32}}()
Ref{trb_control_type{Float64}}()
Ref{trb_control_type{Float128}}()
Ref{trb_time_type{Float32}}()
Ref{trb_time_type{Float64}}()
Ref{trb_time_type{Float128}}()
Ref{trb_inform_type{Float32}}()
Ref{trb_inform_type{Float64}}()
Ref{trb_inform_type{Float128}}()

# Structures for trs
Ref{trs_control_type{Float32}}()
Ref{trs_control_type{Float64}}()
Ref{trs_control_type{Float128}}()
Ref{trs_time_type{Float32}}()
Ref{trs_time_type{Float64}}()
Ref{trs_time_type{Float128}}()
Ref{trs_history_type{Float32}}()
Ref{trs_history_type{Float64}}()
Ref{trs_history_type{Float128}}()
Ref{trs_inform_type{Float32}}()
Ref{trs_inform_type{Float64}}()
Ref{trs_inform_type{Float128}}()

# Structures for tru
Ref{tru_control_type{Float32}}()
Ref{tru_control_type{Float64}}()
Ref{tru_control_type{Float128}}()
Ref{tru_time_type{Float32}}()
Ref{tru_time_type{Float64}}()
Ref{tru_time_type{Float128}}()
Ref{tru_inform_type{Float32}}()
Ref{tru_inform_type{Float64}}()
Ref{tru_inform_type{Float128}}()

# Structures for ugo
Ref{ugo_control_type{Float32}}()
Ref{ugo_control_type{Float64}}()
Ref{ugo_control_type{Float128}}()
Ref{ugo_time_type{Float32}}()
Ref{ugo_time_type{Float64}}()
Ref{ugo_time_type{Float128}}()
Ref{ugo_inform_type{Float32}}()
Ref{ugo_inform_type{Float64}}()
Ref{ugo_inform_type{Float128}}()

# Structures for uls
Ref{uls_control_type{Float32}}()
Ref{uls_control_type{Float64}}()
Ref{uls_control_type{Float128}}()
Ref{uls_inform_type{Float32}}()
Ref{uls_inform_type{Float64}}()
Ref{uls_inform_type{Float128}}()

# Structures for wcp
Ref{wcp_control_type{Float32}}()
Ref{wcp_control_type{Float64}}()
Ref{wcp_control_type{Float128}}()
Ref{wcp_time_type{Float32}}()
Ref{wcp_time_type{Float64}}()
Ref{wcp_time_type{Float128}}()
Ref{wcp_inform_type{Float32}}()
Ref{wcp_inform_type{Float64}}()
Ref{wcp_inform_type{Float128}}()
