# Version
haskey(ENV, "GALAHAD_RELEASE") || error("The environment variable GALAHAD_RELEASE is not defined.")
version = VersionNumber(ENV["GALAHAD_RELEASE"])
version2 = ENV["GALAHAD_RELEASE"]
package = "GALAHAD"

platforms = [
   ("aarch64-apple-darwin-libgfortran5"  , "lib", "dylib"),
   ("aarch64-linux-gnu-libgfortran5"     , "lib", "so"   ),
#  ("aarch64-linux-musl-libgfortran5"    , "lib", "so"   ),
#  ("powerpc64le-linux-gnu-libgfortran5" , "lib", "so"   ),
   ("x86_64-apple-darwin-libgfortran5"   , "lib", "dylib"),
   ("x86_64-linux-gnu-libgfortran5"      , "lib", "so"   ),
#  ("x86_64-linux-musl-libgfortran5"     , "lib", "so"   ),
#  ("x86_64-unknown-freebsd-libgfortran5", "lib", "so"   ),
   ("x86_64-w64-mingw32-libgfortran5"    , "bin", "dll"  ),
]

for (platform, libdir, ext) in platforms

  tarball_int32_name = "$(package)_int32.v$version.$platform.tar.gz"
  tarball_int64_name = "$(package)_int64.v$version.$platform.tar.gz"

  if isfile("products/$(tarball_int32_name)") && isfile("products/$(tarball_int64_name)")

    isdir("products/$platform") && rm("products/$platform", recursive=true)
    mkdir("products/$platform")

    for variant in ("int32", "int64")
      # Unzip the tarball generated by BinaryBuilder.jl
      tarball_name = "$(package)_$(variant).v$version.$platform.tar.gz"
      run(`tar -xzf products/$(tarball_name) -C products/$platform`)

      if isfile("products/$platform/deps.tar.gz")
        # Unzip the tarball of the dependencies
        run(`tar -xzf products/$platform/deps.tar.gz -C products/$platform`)

        # Copy the license of each dependency
        if !isdir("products/$platform/share")
          mkdir("products/$platform/share")
          mkdir("products/$platform/share/licenses")
        end
        for folder in readdir("products/$platform/deps/licenses")
          cp("products/$platform/deps/licenses/$folder", "products/$platform/share/licenses/$folder", force=true)
        end
        rm("products/$platform/deps/licenses", recursive=true)

        # Copy the shared library of each dependency
        for file in readdir("products/$platform/deps")
          cp("products/$platform/deps/$file", "products/$platform/$libdir/$file", force=true)
        end

        # Remove the folder used to unzip the tarball of the dependencies
        rm("products/$platform/deps", recursive=true)
        rm("products/$platform/deps.tar.gz", recursive=true)
      else
        @warn("The tarball deps.tar.gz is missing in $(tarball_name)!")
      end
    end

    # Remove the headers that are not related to GALAHAD
    rm("products/$platform/include/libseq", recursive=true)
    for file in readdir("products/$platform/include")
      if endswith(file, ".h") && !startswith(file, "galahad")
        rm("products/$platform/include/$file")
      end
    end

    # Remove the binaries that are not related to GALAHAD
    for file in readdir("products/$platform/bin")
      if !startswith(file, "run") && !startswith(file, "galahad") && !startswith(file, "buildspec") && !endswith(file, ".dll")
        rm("products/$platform/bin/$file")
      end
    end

    # Remove the libraries that are not dependencies of GALAHAD
    isdir("products/$platform/$libdir/metis") && rm("products/$platform/$libdir/metis", recursive=true)
    isfile("products/$platform/$libdir/libhsl.$ext") && rm("products/$platform/$libdir/libhsl.$ext")
    isfile("products/$platform/$libdir/libcmumps.$ext") && rm("products/$platform/$libdir/libcmumps.$ext")
    isfile("products/$platform/$libdir/libzmumps.$ext") && rm("products/$platform/$libdir/libzmumps.$ext")
    isfile("products/$platform/lib/libcharset.a") && rm("products/$platform/lib/libcharset.a")
    isfile("products/$platform/lib/libz.a") && rm("products/$platform/lib/libz.a")
    isfile("products/$platform/lib/libiconv.a") && rm("products/$platform/lib/libiconv.a")
    isfile("products/$platform/lib/libcutest_single.a") && rm("products/$platform/lib/libcutest_single.a")
    isfile("products/$platform/lib/libcutest_double.a") && rm("products/$platform/lib/libcutest_double.a")
    isfile("products/$platform/lib/libcutest_quadruple.a") && rm("products/$platform/lib/libcutest_quadruple.a")
    isfile("products/$platform/lib/libmetis.dll.a") && rm("products/$platform/lib/libmetis.dll.a")
    for file in readdir("products/$platform/$libdir")
      if startswith(file, "libasan") || startswith(file, "libubsan") || startswith(file, "libtsan") || startswith(file, "libhwasan") || startswith(file, "liblsan")
        rm("products/$platform/$libdir/$file")
      end
    end

    # Create a folder with only the libraries of the dependencies
    mkdir("products/$platform/deps")
    for file in readdir("products/$platform/$libdir")
      if !startswith(file, "libgalahad")
        if platform == "x86_64-w64-mingw32-libgfortran5"
          if !startswith(file, "run") && !startswith(file, "galahad_error") && !startswith(file, "buildspec")
            mv("products/$platform/$libdir/$file", "products/$platform/deps/$file")
          end
        else
          mv("products/$platform/$libdir/$file", "products/$platform/deps/$file")
        end
      end
    end

    # Rename the GALAHAD license directory
    mv("products/$platform/share/licenses/GALAHAD_int64", "products/$platform/share/licenses/GALAHAD")

    # Create the archives *_binaries
    isfile("$(package)_binaries.$version2.$platform.tar.gz") && rm("$(package)_binaries.$version2.$platform.tar.gz")
    isfile("$(package)_binaries.$version2.$platform.zip") && rm("$(package)_binaries.$version2.$platform.zip")
    cd("products/$platform")

    # Create a folder with the version number of the package
    mkdir("$(package)_binaries.$version2")
    for folder in ("include", "share", "modules", "lib", "bin", "deps")
      cp(folder, "$(package)_binaries.$version2/$folder")
    end

    cd("$(package)_binaries.$version2")
    if ext == "dll"
      run(`zip -r --symlinks ../../../$(package)_binaries.$version2.$platform.zip include share modules lib bin deps`)
    else
      run(`tar -czf ../../../$(package)_binaries.$version2.$platform.tar.gz include share modules lib bin deps`)
    end
    cd("../../..")

    # Remove the folder used to unzip the tarball generated by BinaryBuilder.jl
    rm("products/$platform", recursive=true)
  else
    @warn("The tarballs for the platform $platform were not generated!")
  end
end
