task:
  matrix:
    - name: FreeBSD
      freebsd_instance:
        image: freebsd-13-1-release-amd64
    - name: MacOS M1
      macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-base:latest
  dependencies_script: |
    echo $(uname)
    if [ "$(uname)" = "FreeBSD" ]; then
      pkg install -y py39-pip meson bash gcc12
      pip install numpy
    else
      brew install python meson gcc
      pip3 install numpy
    fi
    echo "GALAHAD=$CIRRUS_WORKING_DIR" >> $CIRRUS_ENV
    echo "OMP_CANCELLATION=TRUE" >> $CIRRUS_ENV
    echo "OMP_NESTED=TRUE" >> $CIRRUS_ENV
    echo "OMP_PROC_BIND=TRUE" >> $CIRRUS_ENV
  configure_script: |
    if [ "$(uname -s)" = "FreeBSD" ]; then
      FC=gfortran12 CC=gcc12 CXX=g++12 meson setup builddir --prefix=~/galahad -Dpythoniface=true
    else
      FC=gfortran-12 CC=gcc-12 CXX=g++-12 meson setup builddir --prefix=~/galahad -Dpythoniface=true
    fi
  build_script: |
    meson compile -C builddir
  install_script: |
    meson install -C builddir
  test_script: |
    meson test -C builddir
