task:
  matrix:
    - name: Meson / freebsd/gcc-12/Int32
      freebsd_instance:
        image: freebsd-13-3-release-amd64
      env:
        - JULIA_VERSION: 1
        - INT64: "false"
    - name: Meson / freebsd/gcc-12/Int64
      freebsd_instance:
        image: freebsd-13-3-release-amd64
      env:
        - JULIA_VERSION: 1
        - INT64: "true"
    - name: Meson / macos-silicon/gcc-14/Int32
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      env:
        - JULIA_VERSION: 1
        - INT64: "false"
    - name: Meson / macos-silicon/gcc-14/Int64
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      env:
        - JULIA_VERSION: 1
        - INT64: "true"
  dependencies_script: |
    echo $(uname)
    if [ "$(uname)" = "FreeBSD" ]; then
      pkg install -y py39-pip meson cmake bash gcc12 openblas
      pip install numpy
      echo "JULIA_GALAHAD_LIBRARY_PATH=/usr/local/lib" >> $CIRRUS_ENV
      echo "FC=gfortran12" >> $CIRRUS_ENV
      echo "CC=gcc12" >> $CIRRUS_ENV
      echo "CXX=g++12" >> $CIRRUS_ENV
    else
      brew install python meson gcc@14 openblas numpy
      echo "JULIA_GALAHAD_LIBRARY_PATH=/opt/homebrew/lib" >> $CIRRUS_ENV
      echo "FC=gfortran-14" >> $CIRRUS_ENV
      echo "CC=gcc-14" >> $CIRRUS_ENV
      echo "CXX=g++-14" >> $CIRRUS_ENV
    fi
    echo "JULIA_PROJECT_SUBDIR=GALAHAD.jl" >> $CIRRUS_ENV
    echo "GALAHAD=$CIRRUS_WORKING_DIR" >> $CIRRUS_ENV
    echo "OMP_CANCELLATION=TRUE" >> $CIRRUS_ENV
    echo "OMP_PROC_BIND=TRUE" >> $CIRRUS_ENV
  configure_script: |
    meson setup builddir --buildtype=debug \
                         -Dlibblas= \
                         -Dliblapack= \
                         -Dexamples=true \
                         -Dtests=true \
                         -Dpythoniface=true \
                         -Dgalahad_int64=${INT64}
  build_script: |
    meson compile -C builddir
  install_script: |
    meson install -C builddir
  test_script: |
    meson test -C builddir
  julia_install:
    only_if: $INT64 == 'false'
    script: |
    URL="https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh"
    set -x
    if [ "$(uname -s)" = "Linux" ] && command -v apt; then
        apt update
        apt install -y curl
    fi
    if command -v curl; then
        sh -c "$(curl ${URL})"
    elif command -v wget; then
        sh -c "$(wget ${URL} -q -O-)"
    elif command -v fetch; then
        sh -c "$(fetch ${URL} -o -)"
    fi
  julia_build:
    only_if: $INT64 == 'false'
    script: cirrusjl build
  julia_test:
    only_if: $INT64 == 'false'
    script: cirrusjl test
  on_failure:
    log_artifacts:
      path: builddir/meson-logs/*log.txt
