task:
  matrix:
    - name: FreeBSD/gcc-12/Int32
      freebsd_instance:
        image: freebsd-13-3-release-amd64
      env:
        - JULIA_VERSION: 1
        - INT64: "false"
    - name: FreeBSD/gcc-12/Int64
      freebsd_instance:
        image: freebsd-13-3-release-amd64
      env:
        - JULIA_VERSION: 1
        - INT64: "true"
    - name: macos-silicon/gcc-13/Int32
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      env:
        - JULIA_VERSION: 1
        - INT64: "false"
    - name: macos-silicon/gcc-13/Int64
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
      env:
        - JULIA_VERSION: 1
        - INT64: "true"
  dependencies_script: |
    echo $(uname)
    if [ "$(uname)" = "FreeBSD" ]; then
      pkg install -y py39-pip meson cmake bash gcc12 openblas
      pip install numpy
      echo "JULIA_GALAHAD_LIBRARY_PATH=/usr/local/lib" >> $CIRRUS_ENV
    else
      brew install python meson gcc openblas numpy
      echo "JULIA_GALAHAD_LIBRARY_PATH=/opt/homebrew/lib" >> $CIRRUS_ENV
    fi
    echo "JULIA_PROJECT_SUBDIR=GALAHAD.jl" >> $CIRRUS_ENV
    echo "GALAHAD=$CIRRUS_WORKING_DIR" >> $CIRRUS_ENV
    echo "OMP_CANCELLATION=TRUE" >> $CIRRUS_ENV
    echo "OMP_PROC_BIND=TRUE" >> $CIRRUS_ENV
  configure_script: |
    if [ "$(uname -s)" = "FreeBSD" ]; then
      FC=gfortran12 CC=gcc12 CXX=g++12 meson setup builddir --buildtype=debug \
                                                            -Dexamples=true \
                                                            -Dtests=true \
                                                            -Dpythoniface=true \
                                                            -Dgalahad_int64=${INT64}
    else
      FC=gfortran-13 CC=gcc-13 CXX=g++-13 meson setup builddir --buildtype=debug \
                                                               -Dexamples=true \
                                                               -Dtests=true \
                                                               -Dpythoniface=true \
                                                               -Dgalahad_int64=${INT64} \
                                                               -Dfortran_link_args=${LD_CLASSIC} \
                                                               -Dc_link_args=${LD_CLASSIC}
    fi
  build_script: |
    meson compile -C builddir
  install_script: |
    meson install -C builddir
  test_script: |
    meson test -C builddir
  julia_install_script: |
    URL="https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh"
    set -x
    if [ "$(uname -s)" = "Linux" ] && command -v apt; then
        apt update
        apt install -y curl
    fi
    if command -v curl; then
        sh -c "$(curl ${URL})"
    elif command -v wget; then
        sh -c "$(wget ${URL} -q -O-)"
    elif command -v fetch; then
        sh -c "$(fetch ${URL} -o -)"
    fi
  julia_build_script: |
    cirrusjl build
  julia_test_script: |
    cirrusjl test
  on_failure:
    log_artifacts:
      path: builddir/meson-logs/*log.txt
