[general]
use_julia_native_enum_type = true
print_using_CEnum = false

[codegen]
use_julia_bool = true
use_ccall_macro = true
always_NUL_terminated_string = false

[codegen.macro]
macro_mode = "disable"
