.TH "galahad_convert.h" 3 "Thu Jun 22 2023" "C interfaces to GALAHAD CONVERT" \" -*- nroff -*-
.ad l
.nh
.SH NAME
galahad_convert.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include 'galahad_precision\&.h'\fP
.br
\fC#include 'galahad_cfunctions\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBconvert_control_type\fP"
.br
.ti -1c
.RI "struct \fBconvert_time_type\fP"
.br
.ti -1c
.RI "struct \fBconvert_inform_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBconvert_initialize\fP (void **data, struct \fBconvert_control_type\fP *control, int *status)"
.br
.ti -1c
.RI "void \fBconvert_information\fP (void **data, struct \fBconvert_inform_type\fP *inform, int *status)"
.br
.ti -1c
.RI "void \fBconvert_terminate\fP (void **data, struct \fBconvert_control_type\fP *control, struct \fBconvert_inform_type\fP *inform)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Introduction"
.PP
.SS "Purpose"
Given a real matrix A stored in one format, convert it to another
.PP
Currently, only the control and inform parameters are exposed; these are provided and used by other GALAHAD packages with C interfaces\&.
.SS "Authors"
N\&. I\&. M\&. Gould, STFC-Rutherford Appleton Laboratory, England\&.
.PP
C interface, additionally J\&. Fowkes, STFC-Rutherford Appleton Laboratory\&.
.PP
Julia interface, additionally A\&. Montoison and D\&. Orban, Polytechnique Montréal\&.
.SS "Originally released"
June 2014, C interface February 2022\&. 
.SH "Data Structure Documentation"
.PP 
.SH "struct convert_control_type"
.PP 
control derived type as a C struct 
.PP
\fBData Fields:\fP
.RS 4
bool \fIf_indexing\fP use C or Fortran sparse matrix indexing 
.br
.PP
int \fIerror\fP unit for error messages 
.br
.PP
int \fIout\fP unit for monitor output 
.br
.PP
int \fIprint_level\fP controls level of diagnostic output 
.br
.PP
bool \fItranspose\fP obtain the transpose of the input matrix? 
.br
.PP
bool \fIsum_duplicates\fP add the values of entries in duplicate positions? 
.br
.PP
bool \fIorder\fP order row or column data by increasing index? 
.br
.PP
bool \fIspace_critical\fP if space is critical, ensure allocated arrays are no bigger than needed 
.br
.PP
bool \fIdeallocate_error_fatal\fP exit if any deallocation fails 
.br
.PP
char \fIprefix[31]\fP all output lines will be prefixed by prefix(2:LEN(TRIM(\&.prefix))-1) where prefix contains the required string enclosed in quotes, e\&.g\&. 'string' or 'string' 
.br
.PP
.RE
.PP
.SH "struct convert_time_type"
.PP 
time derived type as a C struct 
.PP
\fBData Fields:\fP
.RS 4
real_wp_ \fItotal\fP total cpu time spent in the package 
.br
.PP
real_wp_ \fIclock_total\fP total clock time spent in the package 
.br
.PP
.RE
.PP
.SH "struct convert_inform_type"
.PP 
inform derived type as a C struct 
.PP
\fBData Fields:\fP
.RS 4
int \fIstatus\fP the return status\&. Possible values are: 
.PD 0

.IP "\(bu" 2
0 a successful conversion\&. 
.IP "\(bu" 2
-1\&. An allocation error occurred\&. A message indicating the offending array is written on unit control\&.error, and the returned allocation status and a string containing the name of the offending array are held in inform\&.alloc_status and inform\&.bad_alloc respectively\&. 
.IP "\(bu" 2
-2\&. A deallocation error occurred\&. A message indicating the offending array is written on unit control\&.error and the returned allocation status and a string containing the name of the offending array are held in inform\&.alloc_status and inform\&.bad_alloc respectively\&. 
.IP "\(bu" 2
-3\&. The restriction n > 0 or m > 0 or requirement that a type contains its relevant string 'coordinate', 'sparse_by_rows', 'sparse_by_columns', 'dense_by_rows' or 'dense_by_columns' has been violated\&. 
.IP "\(bu" 2
-32 provided integer workspace is not large enough\&. 
.IP "\(bu" 2
-33 provided real workspace is not large enough\&. 
.IP "\(bu" 2
-73 an input matrix entry has been repeated\&. 
.IP "\(bu" 2
-79 there are missing optional arguments\&. 
.IP "\(bu" 2
-90 a requested output format is not recognised\&. 
.PP

.br
.PP
int \fIalloc_status\fP the status of the last attempted allocation/deallocation\&. 
.br
.PP
int \fIduplicates\fP the number of duplicates found (-ve = not checked)\&. 
.br
.PP
char \fIbad_alloc[81]\fP the name of the array for which an allocation/deallocation error occurred\&. 
.br
.PP
struct \fBconvert_time_type\fP \fItime\fP timings (see above)\&. 
.br
.PP
.RE
.PP
.SH "Function Documentation"
.PP 
.SS "void convert_initialize (void ** data, struct \fBconvert_control_type\fP * control, int * status)"
Set default control values and initialize private data
.PP
\fBParameters\fP
.RS 4
\fIdata\fP holds private internal data
.br
\fIcontrol\fP is a struct containing control information (see \fBconvert_control_type\fP)
.br
\fIstatus\fP is a scalar variable of type int, that gives the exit status from the package\&. Possible values are (currently): 
.PD 0

.IP "\(bu" 2
0\&. The initialization was succesful\&. 
.PP
.RE
.PP

.SS "void convert_information (void ** data, struct \fBconvert_inform_type\fP * inform, int * status)"
Provides output information
.PP
\fBParameters\fP
.RS 4
\fIdata\fP holds private internal data
.br
\fIinform\fP is a struct containing output information (see \fBconvert_inform_type\fP)
.br
\fIstatus\fP is a scalar variable of type int, that gives the exit status from the package\&. Possible values are (currently): 
.PD 0

.IP "\(bu" 2
0\&. The values were recorded succesfully 
.PP
.RE
.PP

.SS "void convert_terminate (void ** data, struct \fBconvert_control_type\fP * control, struct \fBconvert_inform_type\fP * inform)"
Deallocate all internal private storage
.PP
\fBParameters\fP
.RS 4
\fIdata\fP holds private internal data
.br
\fIcontrol\fP is a struct containing control information (see \fBconvert_control_type\fP)
.br
\fIinform\fP is a struct containing output information (see \fBconvert_inform_type\fP) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for C interfaces to GALAHAD CONVERT from the source code\&.
