.TH "nls_inform_type" 3 "Mon Sep 27 2021" "C interfaces to GALAHAD NLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nls_inform_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nls\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstatus\fP"
.br
.RI "return status\&. See NLS_solve for details "
.ti -1c
.RI "int \fBalloc_status\fP"
.br
.RI "the status of the last attempted allocation/deallocation "
.ti -1c
.RI "char \fBbad_alloc\fP [81]"
.br
.RI "the name of the array for which an allocation/deallocation error ocurred "
.ti -1c
.RI "char \fBbad_eval\fP [13]"
.br
.RI "the name of the user-supplied evaluation routine for which an error ocur "
.ti -1c
.RI "int \fBiter\fP"
.br
.RI "the total number of iterations performed "
.ti -1c
.RI "int \fBcg_iter\fP"
.br
.RI "the total number of CG iterations performed "
.ti -1c
.RI "int \fBc_eval\fP"
.br
.RI "the total number of evaluations of the residual function c(x) "
.ti -1c
.RI "int \fBj_eval\fP"
.br
.RI "the total number of evaluations of the Jacobian J(x) of c(x) "
.ti -1c
.RI "int \fBh_eval\fP"
.br
.RI "the total number of evaluations of the scaled Hessian H(x,y) of c(x) "
.ti -1c
.RI "int \fBfactorization_max\fP"
.br
.RI "the maximum number of factorizations in a sub-problem solve "
.ti -1c
.RI "int \fBfactorization_status\fP"
.br
.RI "the return status from the factorization "
.ti -1c
.RI "int \fBmax_entries_factors\fP"
.br
.RI "the maximum number of entries in the factors "
.ti -1c
.RI "int \fBfactorization_integer\fP"
.br
.RI "the total integer workspace required for the factorization "
.ti -1c
.RI "int \fBfactorization_real\fP"
.br
.RI "the total real workspace required for the factorization "
.ti -1c
.RI "real_wp_ \fBfactorization_average\fP"
.br
.RI "the average number of factorizations per sub-problem solve "
.ti -1c
.RI "real_wp_ \fBobj\fP"
.br
.RI "the value of the objective function 1/2||c(x)||^2_W at the best estimate the solution, x, determined by NLS_solve "
.ti -1c
.RI "real_wp_ \fBnorm_c\fP"
.br
.RI "the norm of the residual ||c(x)||_W at the best estimate of the solution x, determined by NLS_solve "
.ti -1c
.RI "real_wp_ \fBnorm_g\fP"
.br
.RI "the norm of the gradient of ||c(x)||_W of the objective function at the best estimate, x, of the solution determined by NLS_solve "
.ti -1c
.RI "real_wp_ \fBweight\fP"
.br
.RI "the final regularization weight used "
.ti -1c
.RI "struct \fBnls_time_type\fP \fBtime\fP"
.br
.RI "timings (see above) "
.ti -1c
.RI "struct \fBnls_subproblem_inform_type\fP \fBsubproblem_inform\fP"
.br
.RI "inform parameters for subproblem "
.in -1c
.SH "Detailed Description"
.PP 
inform derived type as a C struct 

.SH "Author"
.PP 
Generated automatically by Doxygen for C interfaces to GALAHAD NLS from the source code\&.
