.TH "nls_time_type" 3 "Mon Sep 27 2021" "C interfaces to GALAHAD NLS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nls_time_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nls\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "real_sp_ \fBtotal\fP"
.br
.RI "the total CPU time spent in the package "
.ti -1c
.RI "real_sp_ \fBpreprocess\fP"
.br
.RI "the CPU time spent preprocessing the problem "
.ti -1c
.RI "real_sp_ \fBanalyse\fP"
.br
.RI "the CPU time spent analysing the required matrices prior to factorizatio "
.ti -1c
.RI "real_sp_ \fBfactorize\fP"
.br
.RI "the CPU time spent factorizing the required matrices "
.ti -1c
.RI "real_sp_ \fBsolve\fP"
.br
.RI "the CPU time spent computing the search direction "
.ti -1c
.RI "real_wp_ \fBclock_total\fP"
.br
.RI "the total clock time spent in the package "
.ti -1c
.RI "real_wp_ \fBclock_preprocess\fP"
.br
.RI "the clock time spent preprocessing the problem "
.ti -1c
.RI "real_wp_ \fBclock_analyse\fP"
.br
.RI "the clock time spent analysing the required matrices prior to factorizat "
.ti -1c
.RI "real_wp_ \fBclock_factorize\fP"
.br
.RI "the clock time spent factorizing the required matrices "
.ti -1c
.RI "real_wp_ \fBclock_solve\fP"
.br
.RI "the clock time spent computing the search direction "
.in -1c
.SH "Detailed Description"
.PP 
time derived type as a C struct 

.SH "Author"
.PP 
Generated automatically by Doxygen for C interfaces to GALAHAD NLS from the source code\&.
