.TH "trb_inform_type" 3 "Tue Aug 31 2021" "C interfaces to GALAHAD TRB" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trb_inform_type
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <trb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstatus\fP"
.br
.RI "return status\&. See TRB_solve for details "
.ti -1c
.RI "int \fBalloc_status\fP"
.br
.RI "the status of the last attempted allocation/deallocation "
.ti -1c
.RI "char \fBbad_alloc\fP [81]"
.br
.RI "the name of the array for which an allocation/deallocation error ocurred "
.ti -1c
.RI "int \fBn_free\fP"
.br
.RI "the number of variables that are free from their bounds "
.ti -1c
.RI "int \fBiter\fP"
.br
.RI "the total number of iterations performed "
.ti -1c
.RI "int \fBcg_iter\fP"
.br
.RI "the total number of CG iterations performed "
.ti -1c
.RI "int \fBcg_maxit\fP"
.br
.RI "the maximum number of CG iterations allowed per iteration "
.ti -1c
.RI "int \fBf_eval\fP"
.br
.RI "the total number of evaluations of the objection function "
.ti -1c
.RI "int \fBg_eval\fP"
.br
.RI "the total number of evaluations of the gradient of the objection functio "
.ti -1c
.RI "int \fBh_eval\fP"
.br
.RI "the total number of evaluations of the Hessian of the objection function "
.ti -1c
.RI "int \fBfactorization_max\fP"
.br
.RI "the maximum number of factorizations in a sub-problem solve "
.ti -1c
.RI "int \fBfactorization_status\fP"
.br
.RI "the return status from the factorization "
.ti -1c
.RI "int \fBmax_entries_factors\fP"
.br
.RI "the maximum number of entries in the factors "
.ti -1c
.RI "int \fBfactorization_integer\fP"
.br
.RI "the total integer workspace required for the factorization "
.ti -1c
.RI "int \fBfactorization_real\fP"
.br
.RI "the total real workspace required for the factorization "
.ti -1c
.RI "real_wp_ \fBobj\fP"
.br
.RI "the value of the objective function at the best estimate of the solution determined by TRB_solve "
.ti -1c
.RI "real_wp_ \fBnorm_pg\fP"
.br
.RI "the norm of the projected gradient of the objective function at the best estimate of the solution determined by TRB_solve "
.ti -1c
.RI "real_wp_ \fBradius\fP"
.br
.RI "the current value of the trust-region radius "
.ti -1c
.RI "struct \fBtrb_time_type\fP \fBtime\fP"
.br
.RI "timings (see above) "
.in -1c
.SH "Detailed Description"
.PP 
inform derived type as a C struct 

.SH "Author"
.PP 
Generated automatically by Doxygen for C interfaces to GALAHAD TRB from the source code\&.
