! THIS VERSION: GALAHAD 5.2 - 2025-04-17 AT 16:20 GMT.

#include "galahad_modules.h"

SUBROUTINE GALAHAD_load_routines_r(libname)
    USE CUTEST_TRAMPOLINE_precision
    USE ISO_C_BINDING, ONLY : C_CHAR
    CHARACTER ( KIND = C_CHAR ), DIMENSION( * ), INTENT( IN ) :: libname
    CALL CUTEST_LOAD_ROUTINES(libname)
END SUBROUTINE GALAHAD_load_routines_r

SUBROUTINE GALAHAD_unload_routines_r()
    USE CUTEST_TRAMPOLINE_precision
    CALL CUTEST_UNLOAD_ROUTINES()
END SUBROUTINE GALAHAD_unload_routines_r
