/mainpage/a   @file
s/\\f\$//g
s/\\mathbf{x}/x/g
s/\\mathbf{f(x)}/f(x)/g
s/\\partial/partial/g
s/\\zero/0/g
s/\\nabla/nabla/g
s/\\equiv/=/g
s/\\Delta/Delta/g
s/\\alpha/alpha/g
s/\\sigma/sigma/g
s/\\rho/rho/g
s/\\sqrt/sqrt/g
s/\\lambda/lambda/g
s/\\ell/l/g
s/\\eta/eta/g
s/\\ast/*/g
s/\\cdot/*/g
s/\\|/||/g
s/\\mathbf{w_i}/w_i/g
s/\\mathbf{i=1,\ldots,m}/i=1,...,m/g
s/\\ldots/.../g
s~\\leq~<=~g
s~\\geq~>=~g
s~\\neq~/=~g
s~\\frac{1}{2}~1/2~g
s/\\mathbf//g
/\\label{examples}/d
