! THIS VERSION: GALAHAD 4.3 - 2024-01-05 AT 14:30 GMT.

      DOUBLE PRECISION FUNCTION FA14AD( ix, i )
      USE GALAHAD_KINDS
      INTEGER ( KIND = ip_ ) :: ix, i
      END FUNCTION FA14AD

      SUBROUTINE FA14ID( ix )
      USE GALAHAD_KINDS
      INTEGER  ( KIND = ip_ ) :: ix
      END SUBROUTINE FA14ID
