! THIS VERSION: GALAHAD 4.3 - 2024-01-05 AT 14:30 GMT.

      REAL FUNCTION FA14A( ix, i )
      USE GALAHAD_KINDS
      INTEGER ( KIND = ip_ ) :: ix, i
      END FUNCTION FA14A

      SUBROUTINE FA14I( ix )
      USE GALAHAD_KINDS
      INTEGER ( KIND = ip_ ) :: ix
      END SUBROUTINE FA14I
