! THIS VERSION: GALAHAD 4.3 - 2024-01-04 AT 14:30 GMT.

#ifdef GALAHAD_64BIT_INTEGER
  INTEGER, PARAMETER :: ip_ = INT64
#else
  INTEGER, PARAMETER :: ip_ = INT32
#endif

      REAL FUNCTION FA14A( ix, i )
      INTEGER ( KIND = ip_ ) :: ix, i
      END FUNCTION FA14A

      SUBROUTINE FA14I( ix )
      INTEGER ( KIND = ip_ ) :: ix
      END SUBROUTINE FA14I
