! THIS VERSION: 28/03/2021 AT 15:00:00 GMT.

!-*-*-*-  G A L A H A D  -  D U M M Y   P A R D I S O  R O U T I N E S  -*-*-*-

  SUBROUTINE PARDISO_S( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,          &
                        PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: MAXFCT
  INTEGER, INTENT(IN)    :: MNUM
  INTEGER, INTENT(IN)    :: MTYPE
  INTEGER, INTENT(IN)    :: PHASE
  INTEGER, INTENT(IN)    :: N
  INTEGER, INTENT(IN)    :: IA(*)
  INTEGER, INTENT(IN)    :: JA(*)
  INTEGER, INTENT(INOUT) :: PERM(*)
  INTEGER, INTENT(IN)    :: NRHS
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(IN)    :: MSGLVL
  INTEGER, INTENT(OUT)   :: ERROR

  REAL( KIND = sp ), INTENT(IN)    :: A(*)
  REAL( KIND = sp ), INTENT(INOUT) :: B(*)
  REAL( KIND = sp ), INTENT(OUT)   :: X(*)
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_S

  SUBROUTINE PARDISO_D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,          &
                        PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: MAXFCT
  INTEGER, INTENT(IN)    :: MNUM
  INTEGER, INTENT(IN)    :: MTYPE
  INTEGER, INTENT(IN)    :: PHASE
  INTEGER, INTENT(IN)    :: N
  INTEGER, INTENT(IN)    :: IA(*)
  INTEGER, INTENT(IN)    :: JA(*)
  INTEGER, INTENT(INOUT) :: PERM(*)
  INTEGER, INTENT(IN)    :: NRHS
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(IN)    :: MSGLVL
  INTEGER, INTENT(OUT)   :: ERROR

  REAL( KIND = dp ), INTENT(IN)    :: A(*)
  REAL( KIND = dp ), INTENT(INOUT) :: B(*)
  REAL( KIND = dp ), INTENT(OUT)   :: X(*)
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_D

  SUBROUTINE PARDISO_SC( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,         &
                         PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: MAXFCT
  INTEGER, INTENT(IN)    :: MNUM
  INTEGER, INTENT(IN)    :: MTYPE
  INTEGER, INTENT(IN)    :: PHASE
  INTEGER, INTENT(IN)    :: N
  INTEGER, INTENT(IN)    :: IA(*)
  INTEGER, INTENT(IN)    :: JA(*)
  INTEGER, INTENT(INOUT) :: PERM(*)
  INTEGER, INTENT(IN)    :: NRHS
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(IN)    :: MSGLVL
  INTEGER, INTENT(OUT)   :: ERROR

  COMPLEX( KIND = sp ), INTENT(IN)    :: A(*)
  COMPLEX( KIND = sp ), INTENT(INOUT) :: B(*)
  COMPLEX( KIND = sp ), INTENT(OUT)   :: X(*)
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_SC

  SUBROUTINE PARDISO_DC( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,         &
                         PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: MAXFCT
  INTEGER, INTENT(IN)    :: MNUM
  INTEGER, INTENT(IN)    :: MTYPE
  INTEGER, INTENT(IN)    :: PHASE
  INTEGER, INTENT(IN)    :: N
  INTEGER, INTENT(IN)    :: IA(*)
  INTEGER, INTENT(IN)    :: JA(*)
  INTEGER, INTENT(INOUT) :: PERM(*)
  INTEGER, INTENT(IN)    :: NRHS
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(IN)    :: MSGLVL
  INTEGER, INTENT(OUT)   :: ERROR
  COMPLEX( KIND = dp ), INTENT(IN)    :: A(*)
  COMPLEX( KIND = dp ), INTENT(INOUT) :: B(*)
  COMPLEX( KIND = dp ), INTENT(OUT)   :: X(*)
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_DC

  SUBROUTINE PARDISO_S_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,       &
                           PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: MAXFCT
  INTEGER, INTENT(IN)    :: MNUM
  INTEGER, INTENT(IN)    :: MTYPE
  INTEGER, INTENT(IN)    :: PHASE
  INTEGER, INTENT(IN)    :: N
  INTEGER, INTENT(IN)    :: IA(*)
  INTEGER, INTENT(IN)    :: JA(*)
  INTEGER, INTENT(INOUT) :: PERM(*)
  INTEGER, INTENT(IN)    :: NRHS
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(IN)    :: MSGLVL
  INTEGER, INTENT(OUT)   :: ERROR
  REAL( KIND = sp ), INTENT(IN)    :: A(*)
  REAL( KIND = sp ), INTENT(INOUT) :: B(N,*)
  REAL( KIND = sp ), INTENT(OUT)   :: X(N,*)
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_S_2D

  SUBROUTINE PARDISO_D_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA, JA,       &
                           PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: MAXFCT
  INTEGER, INTENT(IN)    :: MNUM
  INTEGER, INTENT(IN)    :: MTYPE
  INTEGER, INTENT(IN)    :: PHASE
  INTEGER, INTENT(IN)    :: N
  INTEGER, INTENT(IN)    :: IA(*)
  INTEGER, INTENT(IN)    :: JA(*)
  INTEGER, INTENT(INOUT) :: PERM(*)
  INTEGER, INTENT(IN)    :: NRHS
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(IN)    :: MSGLVL
  INTEGER, INTENT(OUT)   :: ERROR
  REAL( KIND = dp ), INTENT(IN)    :: A(*)
  REAL( KIND = dp ), INTENT(INOUT) :: B(N,*)
  REAL( KIND = dp ), INTENT(OUT)   :: X(N,*)
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_D_2D

  SUBROUTINE PARDISO_SC_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,          &
                            JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: MAXFCT
  INTEGER, INTENT(IN)    :: MNUM
  INTEGER, INTENT(IN)    :: MTYPE
  INTEGER, INTENT(IN)    :: PHASE
  INTEGER, INTENT(IN)    :: N
  INTEGER, INTENT(IN)    :: IA(*)
  INTEGER, INTENT(IN)    :: JA(*)
  INTEGER, INTENT(INOUT) :: PERM(*)
  INTEGER, INTENT(IN)    :: NRHS
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(IN)    :: MSGLVL
  INTEGER, INTENT(OUT)   :: ERROR
  COMPLEX( KIND = sp ), INTENT(IN)    :: A(*)
  COMPLEX( KIND = sp ), INTENT(INOUT) :: B(N,*)
  COMPLEX( KIND = sp ), INTENT(OUT)   :: X(N,*)
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_SC_2D

  SUBROUTINE PARDISO_DC_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,          &
                            JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: MAXFCT
  INTEGER, INTENT(IN)    :: MNUM
  INTEGER, INTENT(IN)    :: MTYPE
  INTEGER, INTENT(IN)    :: PHASE
  INTEGER, INTENT(IN)    :: N
  INTEGER, INTENT(IN)    :: IA(*)
  INTEGER, INTENT(IN)    :: JA(*)
  INTEGER, INTENT(INOUT) :: PERM(*)
  INTEGER, INTENT(IN)    :: NRHS
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(IN)    :: MSGLVL
  INTEGER, INTENT(OUT)   :: ERROR
  COMPLEX( KIND = dp ), INTENT(IN)    :: A(*)
  COMPLEX( KIND = dp ), INTENT(INOUT) :: B(N,*)
  COMPLEX( KIND = dp ), INTENT(OUT)   :: X(N,*)
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_DC_2D

  SUBROUTINE PARDISO_S_64( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,           &
                           JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MAXFCT
  INTEGER( KIND = long ), INTENT(IN)    :: MNUM
  INTEGER( KIND = long ), INTENT(IN)    :: MTYPE
  INTEGER( KIND = long ), INTENT(IN)    :: PHASE
  INTEGER( KIND = long ), INTENT(IN)    :: N
  INTEGER( KIND = long ), INTENT(IN)    :: IA(*)
  INTEGER( KIND = long ), INTENT(IN)    :: JA(*)
  INTEGER( KIND = long ), INTENT(INOUT) :: PERM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: NRHS
  INTEGER( KIND = long ), INTENT(INOUT) :: IPARM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MSGLVL
  INTEGER( KIND = long ), INTENT(OUT)   :: ERROR
  REAL( KIND = sp ), INTENT(IN)    :: A(*)
  REAL( KIND = sp ), INTENT(INOUT) :: B(*)
  REAL( KIND = sp ), INTENT(OUT)   :: X(*)
  ERROR = INT( GALAHAD_unavailable_option, KIND =  long )
  END SUBROUTINE PARDISO_S_64

  SUBROUTINE PARDISO_D_64( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,           &
                           JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MAXFCT
  INTEGER( KIND = long ), INTENT(IN)    :: MNUM
  INTEGER( KIND = long ), INTENT(IN)    :: MTYPE
  INTEGER( KIND = long ), INTENT(IN)    :: PHASE
  INTEGER( KIND = long ), INTENT(IN)    :: N
  INTEGER( KIND = long ), INTENT(IN)    :: IA(*)
  INTEGER( KIND = long ), INTENT(IN)    :: JA(*)
  INTEGER( KIND = long ), INTENT(INOUT) :: PERM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: NRHS
  INTEGER( KIND = long ), INTENT(INOUT) :: IPARM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MSGLVL
  INTEGER( KIND = long ), INTENT(OUT)   :: ERROR
  REAL( KIND = dp ), INTENT(IN)    :: A(*)
  REAL( KIND = dp ), INTENT(INOUT) :: B(*)
  REAL( KIND = dp ), INTENT(OUT)   :: X(*)
  ERROR = INT( GALAHAD_unavailable_option, KIND = long )
  END SUBROUTINE PARDISO_D_64

  SUBROUTINE PARDISO_SC_64( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,          &
                            JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MAXFCT
  INTEGER( KIND = long ), INTENT(IN)    :: MNUM
  INTEGER( KIND = long ), INTENT(IN)    :: MTYPE
  INTEGER( KIND = long ), INTENT(IN)    :: PHASE
  INTEGER( KIND = long ), INTENT(IN)    :: N
  INTEGER( KIND = long ), INTENT(IN)    :: IA(*)
  INTEGER( KIND = long ), INTENT(IN)    :: JA(*)
  INTEGER( KIND = long ), INTENT(INOUT) :: PERM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: NRHS
  INTEGER( KIND = long ), INTENT(INOUT) :: IPARM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MSGLVL
  INTEGER( KIND = long ), INTENT(OUT)   :: ERROR
  COMPLEX( KIND = sp ), INTENT(IN)    :: A(*)
  COMPLEX( KIND = sp ), INTENT(INOUT) :: B(*)
  COMPLEX( KIND = sp ), INTENT(OUT)   :: X(*)
  ERROR = INT( GALAHAD_unavailable_option, KIND = long )
  END SUBROUTINE PARDISO_SC_64

  SUBROUTINE PARDISO_DC_64( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,          &
                            JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MAXFCT
  INTEGER( KIND = long ), INTENT(IN)    :: MNUM
  INTEGER( KIND = long ), INTENT(IN)    :: MTYPE
  INTEGER( KIND = long ), INTENT(IN)    :: PHASE
  INTEGER( KIND = long ), INTENT(IN)    :: N
  INTEGER( KIND = long ), INTENT(IN)    :: IA(*)
  INTEGER( KIND = long ), INTENT(IN)    :: JA(*)
  INTEGER( KIND = long ), INTENT(INOUT) :: PERM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: NRHS
  INTEGER( KIND = long ), INTENT(INOUT) :: IPARM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MSGLVL
  INTEGER( KIND = long ), INTENT(OUT)   :: ERROR
  COMPLEX( KIND = dp ), INTENT(IN)    :: A(*)
  COMPLEX( KIND = dp ), INTENT(INOUT) :: B(*)
  COMPLEX( KIND = dp ), INTENT(OUT)   :: X(*)
  ERROR = INT( GALAHAD_unavailable_option, KIND = long )
  END SUBROUTINE PARDISO_DC_64

  SUBROUTINE PARDISO_S_64_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,        &
                              JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MAXFCT
  INTEGER( KIND = long ), INTENT(IN)    :: MNUM
  INTEGER( KIND = long ), INTENT(IN)    :: MTYPE
  INTEGER( KIND = long ), INTENT(IN)    :: PHASE
  INTEGER( KIND = long ), INTENT(IN)    :: N
  INTEGER( KIND = long ), INTENT(IN)    :: IA(*)
  INTEGER( KIND = long ), INTENT(IN)    :: JA(*)
  INTEGER( KIND = long ), INTENT(INOUT) :: PERM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: NRHS
  INTEGER( KIND = long ), INTENT(INOUT) :: IPARM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MSGLVL
  INTEGER( KIND = long ), INTENT(OUT)   :: ERROR
  REAL( KIND = sp ), INTENT(IN)    :: A(*)
  REAL( KIND = sp ), INTENT(INOUT) :: B(N,*)
  REAL( KIND = sp ), INTENT(OUT)   :: X(N,*)
  ERROR = INT( GALAHAD_unavailable_option, KIND = long )
  END SUBROUTINE PARDISO_S_64_2D

  SUBROUTINE PARDISO_D_64_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,        &
                              JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MAXFCT
  INTEGER( KIND = long ), INTENT(IN)    :: MNUM
  INTEGER( KIND = long ), INTENT(IN)    :: MTYPE
  INTEGER( KIND = long ), INTENT(IN)    :: PHASE
  INTEGER( KIND = long ), INTENT(IN)    :: N
  INTEGER( KIND = long ), INTENT(IN)    :: IA(*)
  INTEGER( KIND = long ), INTENT(IN)    :: JA(*)
  INTEGER( KIND = long ), INTENT(INOUT) :: PERM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: NRHS
  INTEGER( KIND = long ), INTENT(INOUT) :: IPARM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MSGLVL
  INTEGER( KIND = long ), INTENT(OUT)   :: ERROR
  REAL( KIND = dp ), INTENT(IN)    :: A(*)
  REAL( KIND = dp ), INTENT(INOUT) :: B(N,*)
  REAL( KIND = dp ), INTENT(OUT)   :: X(N,*)
  ERROR = INT( GALAHAD_unavailable_option, KIND = long )
  END SUBROUTINE PARDISO_D_64_2D

  SUBROUTINE PARDISO_SC_64_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,       &
                               JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR)
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MAXFCT
  INTEGER( KIND = long ), INTENT(IN)    :: MNUM
  INTEGER( KIND = long ), INTENT(IN)    :: MTYPE
  INTEGER( KIND = long ), INTENT(IN)    :: PHASE
  INTEGER( KIND = long ), INTENT(IN)    :: N
  INTEGER( KIND = long ), INTENT(IN)    :: IA(*)
  INTEGER( KIND = long ), INTENT(IN)    :: JA(*)
  INTEGER( KIND = long ), INTENT(INOUT) :: PERM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: NRHS
  INTEGER( KIND = long ), INTENT(INOUT) :: IPARM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MSGLVL
  INTEGER( KIND = long ), INTENT(OUT)   :: ERROR
  COMPLEX( KIND = sp ), INTENT(IN)    :: A(*)
  COMPLEX( KIND = sp ), INTENT(INOUT) :: B(N,*)
  COMPLEX( KIND = sp ), INTENT(OUT)   :: X(N,*)
  ERROR = INT( GALAHAD_unavailable_option, KIND = long )
  END SUBROUTINE PARDISO_SC_64_2D

  SUBROUTINE PARDISO_DC_64_2D( PT, MAXFCT, MNUM, MTYPE, PHASE, N, A, IA,       &
                               JA, PERM, NRHS, IPARM, MSGLVL, B, X, ERROR)
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MAXFCT
  INTEGER( KIND = long ), INTENT(IN)    :: MNUM
  INTEGER( KIND = long ), INTENT(IN)    :: MTYPE
  INTEGER( KIND = long ), INTENT(IN)    :: PHASE
  INTEGER( KIND = long ), INTENT(IN)    :: N
  INTEGER( KIND = long ), INTENT(IN)    :: IA(*)
  INTEGER( KIND = long ), INTENT(IN)    :: JA(*)
  INTEGER( KIND = long ), INTENT(INOUT) :: PERM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: NRHS
  INTEGER( KIND = long ), INTENT(INOUT) :: IPARM(*)
  INTEGER( KIND = long ), INTENT(IN)    :: MSGLVL
  INTEGER( KIND = long ), INTENT(OUT)   :: ERROR
  COMPLEX( KIND = dp ), INTENT(IN)    :: A(*)
  COMPLEX( KIND = dp ), INTENT(INOUT) :: B(N,*)
  COMPLEX( KIND = dp ), INTENT(OUT)   :: X(N,*)
  ERROR = INT( GALAHAD_unavailable_option, KIND = long )
  END SUBROUTINE PARDISO_DC_64_2D

  SUBROUTINE PARDISO_GETDIAG_D(PT,DIAG_FACT,DIAG_A,MNUM,ERROR)
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  REAL( KIND = dp ), INTENT(INOUT) :: DIAG_FACT(*), DIAG_A(*)
  INTEGER, INTENT(IN)            :: MNUM
  INTEGER, INTENT(INOUT)         :: ERROR
  ERROR = GALAHAD_unavailable_option
  END

  SUBROUTINE PARDISO_GETDIAG_Z(PT,DIAG_FACT,DIAG_A,MNUM,ERROR)
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  COMPLEX( KIND = dp ), INTENT(INOUT)   :: DIAG_FACT(*), DIAG_A(*)
  INTEGER, INTENT(IN) :: MNUM
  INTEGER, INTENT(INOUT):: ERROR
  ERROR = GALAHAD_unavailable_option
  END

  SUBROUTINE PARDISO_EXPORT_D(PT,VALUES,IA,JA,STEP,IPARM,ERROR)
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  REAL( KIND = dp ), INTENT(INOUT) :: VALUES(*)
  INTEGER, INTENT(INOUT) :: IA(*), JA(*)
  INTEGER, INTENT(IN)    :: STEP
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(OUT)   :: ERROR
  ERROR = GALAHAD_unavailable_option
  END

  SUBROUTINE PARDISO_EXPORT_S(PT,VALUES,IA,JA,STEP,IPARM,ERROR)
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  REAL( KIND = sp ), INTENT(INOUT) :: VALUES(*)
  INTEGER, INTENT(INOUT) :: IA(*), JA(*)
  INTEGER, INTENT(IN)    :: STEP
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(OUT)   :: ERROR
  ERROR = GALAHAD_unavailable_option
  END

  SUBROUTINE PARDISO_EXPORT_C(PT,VALUES,IA,JA,STEP,IPARM,ERROR)
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: sp = KIND( 1.0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  COMPLEX( KIND = sp ), INTENT(INOUT) :: VALUES(*)
  INTEGER, INTENT(INOUT) :: IA(*), JA(*)
  INTEGER, INTENT(IN)    :: STEP
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(OUT)   :: ERROR
  ERROR = GALAHAD_unavailable_option
  END

  SUBROUTINE PARDISO_EXPORT_Z(PT,VALUES,IA,JA,STEP,IPARM,ERROR)
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  COMPLEX( KIND = dp ), INTENT(INOUT) :: VALUES(*)
  INTEGER, INTENT(INOUT) :: IA(*), JA(*)
  INTEGER, INTENT(IN)    :: STEP
  INTEGER, INTENT(INOUT) :: IPARM(*)
  INTEGER, INTENT(OUT)   :: ERROR
  ERROR = GALAHAD_unavailable_option
  END

  SUBROUTINE PARDISO_HANDLE_STORE( PT, STORE_NAME, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  CHARACTER, INTENT(IN)  :: STORE_NAME(*)
  INTEGER,   INTENT(OUT) :: ERROR
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_HANDLE_STORE

  SUBROUTINE PARDISO_HANDLE_STORE_64( PT, STORE_NAME, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  CHARACTER, INTENT(IN)  :: STORE_NAME(*)
  INTEGER ( KIND = long ), INTENT(OUT) :: ERROR
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_HANDLE_STORE_64

  SUBROUTINE PARDISO_HANDLE_RESTORE( PT, STORE_NAME, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  CHARACTER, INTENT(IN)  :: STORE_NAME(*)
  INTEGER, INTENT(OUT) :: ERROR
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_HANDLE_RESTORE

  SUBROUTINE PARDISO_HANDLE_RESTORE_64( PT, STORE_NAME, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  CHARACTER, INTENT(IN)  :: STORE_NAME(*)
  INTEGER ( KIND = long ), INTENT(OUT) :: ERROR
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_HANDLE_RESTORE_64

  SUBROUTINE PARDISO_HANDLE_DELETE( STORE_NAME, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  CHARACTER, INTENT(IN)  :: STORE_NAME(*)
  INTEGER, INTENT(OUT) :: ERROR
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_HANDLE_DELETE

  SUBROUTINE PARDISO_HANDLE_DELETE_64( STORE_NAME, ERROR )
  USE MKL_PARDISO_PRIVATE
  USE GALAHAD_SYMBOLS
  INTEGER, PARAMETER :: long = SELECTED_INT_KIND( 18 )
  CHARACTER, INTENT(IN)  :: STORE_NAME(*)
  INTEGER ( KIND = long ), INTENT(OUT) :: ERROR
  ERROR = GALAHAD_unavailable_option
  END SUBROUTINE PARDISO_HANDLE_DELETE_64

  FUNCTION PARDISO_GETENV(PT, OptName, StrVal)
  USE MKL_PARDISO_PRIVATE
  INTEGER PARDISO_GETENV
  TYPE(MKL_PARDISO_HANDLE), INTENT(IN)  :: PT(*)
  INTEGER, INTENT(IN)  :: OptName
  CHARACTER, INTENT(OUT) :: StrVal(*)
  END FUNCTION PARDISO_GETENV

  FUNCTION PARDISO_GETENV_F(PT, OptName, StrVal)
  USE MKL_PARDISO_PRIVATE
  INTEGER PARDISO_GETENV_F
  TYPE(MKL_PARDISO_HANDLE), INTENT(IN)  :: PT(*)
  INTEGER, INTENT(IN)  :: OptName
  CHARACTER(*), INTENT(OUT) :: StrVal
  END FUNCTION PARDISO_GETENV_F

  FUNCTION PARDISO_SETENV(PT, OptName, StrVal)
  USE MKL_PARDISO_PRIVATE
  INTEGER PARDISO_SETENV
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: OptName
  INTEGER, INTENT(IN)    :: StrVal(*)
  END FUNCTION PARDISO_SETENV

  FUNCTION PARDISO_SETENV_F(PT, OptName, StrVal)
  USE MKL_PARDISO_PRIVATE
  INTEGER PARDISO_SETENV_F
  TYPE(MKL_PARDISO_HANDLE), INTENT(INOUT) :: PT(*)
  INTEGER, INTENT(IN)    :: OptName
  CHARACTER(*), INTENT(IN)    :: StrVal
  END FUNCTION PARDISO_SETENV_F

  FUNCTION MKL_PARDISO_PIVOT( AII, BII, EPS)
  INTEGER, PARAMETER :: dp = KIND( 1.0D+0 )
  REAL( KIND = dp ) :: AII, BII, EPS
  INTEGER   MKL_PARDISO_PIVOT
  END

!  SUBROUTINE PARDISOINIT(PT, MTYPE, IPARM)
!  USE MKL_PARDISO_PRIVATE
!  TYPE(MKL_PARDISO_HANDLE), INTENT(OUT) :: PT(*)
!  INTEGER, INTENT(IN)    :: MTYPE
!  INTEGER, INTENT(OUT) :: IPARM(*)
!  END SUBROUTINE PARDISOINIT

