! THIS VERSION: GALAHAD 4.1 - 2022-11-21 AT 10:00 GMT.

!-*-*-*-  G A L A H A D  -  D U M M Y   M P I   S U B R O U T I N E  -*-*-*-*-

  SUBROUTINE MPI_INIT( ierr )
  INTEGER ierr
  ierr = - 999
  END SUBROUTINE MPI_INIT

  SUBROUTINE MPI_FINALIZE( ierr )
  INTEGER ierr
  END SUBROUTINE MPI_FINALIZE
