#ifdef GALAHAD_64BIT_INTEGER
#define GALAHAD_BLAS_interface GALAHAD_BLAS_interface_64
#ifdef GALAHAD_NO_UNDERSCORE_64BIT_INTEGER
#define DASUM  DASUM64
#define DCABS1 DCABS164
#define DDOT   DDOT64
#define DNRM2  DNRM264
#define DZNRM2 DZNRM264
#define LSAME  LSAME64
#define SASUM  SASUM64
#define SDOT   SDOT64
#define SNRM2  SNRM264
#define DAXPY  DAXPY64
#define DCOPY  DCOPY64
#define DGEMM  DGEMM64
#define DGEMV  DGEMV64
#define DGER   DGER64
#define DROT   DROT64
#define DROTG  DROTG64
#define DSCAL  DSCAL64
#define DSWAP  DSWAP64
#define DSYMM  DSYMM64
#define DSYMV  DSYMV64
#define DSYR   DSYR64
#define DSYR2  DSYR264
#define DSYR2K DSYR2K64
#define DSYRK  DSYRK64
#define DTBSV  DTBSV64
#define DTPMV  DTPMV64
#define DTPSV  DTPSV64
#define DTRMM  DTRMM64
#define DTRMV  DTRMV64
#define DTRSM  DTRSM64
#define DTRSV  DTRSV64
#define SAXPY  SAXPY64
#define SCOPY  SCOPY64
#define SGEMM  SGEMM64
#define SGEMV  SGEMV64
#define SGER   SGER64
#define SROT   SROT64
#define SROTG  SROTG64
#define SSCAL  SSCAL64
#define SSWAP  SSWAP64
#define SSYMM  SSYMM64
#define SSYMV  SSYMV64
#define SSYR   SSYR64
#define SSYR2  SSYR264
#define SSYR2K SSYR2K64
#define SSYRK  SSYRK64
#define STBSV  STBSV64
#define STPMV  STPMV64
#define STPSV  STPSV64
#define STRMM  STRMM64
#define STRMV  STRMV64
#define STRSM  STRSM64
#define STRSV  STRSV64
#define XERBLA XERBLA64
#define ZCOPY  ZCOPY64
#define ZDSCAL ZDSCAL64
#define ZGEMM  ZGEMM64
#define ZGEMV  ZGEMV64
#define ZGERC  ZGERC64
#define ZGERU  ZGERU64
#define ZHER   ZHER64
#define ZSCAL  ZSCAL64
#define ZSWAP  ZSWAP64
#define ZTRMM  ZTRMM64
#define ZTRMV  ZTRMV64
#define ZTRSM  ZTRSM64
#elif GALAHAD_DOUBLE_UNDERSCORE_64BIT_INTEGER
#define DASUM  DASUM__64
#define DCABS1 DCABS1__64
#define DDOT   DDOT__64
#define DNRM2  DNRM2__64
#define DZNRM2 DZNRM2__64
#define LSAME  LSAME__64
#define SASUM  SASUM__64
#define SDOT   SDOT__64
#define SNRM2  SNRM2__64
#define DAXPY  DAXPY__64
#define DCOPY  DCOPY__64
#define DGEMM  DGEMM__64
#define DGEMV  DGEMV__64
#define DGER   DGER__64
#define DROT   DROT__64
#define DROTG  DROTG__64
#define DSCAL  DSCAL__64
#define DSWAP  DSWAP__64
#define DSYMM  DSYMM__64
#define DSYMV  DSYMV__64
#define DSYR   DSYR__64
#define DSYR2  DSYR2__64
#define DSYR2K DSYR2K__64
#define DSYRK  DSYRK__64
#define DTBSV  DTBSV__64
#define DTPMV  DTPMV__64
#define DTPSV  DTPSV__64
#define DTRMM  DTRMM__64
#define DTRMV  DTRMV__64
#define DTRSM  DTRSM__64
#define DTRSV  DTRSV__64
#define SAXPY  SAXPY__64
#define SCOPY  SCOPY__64
#define SGEMM  SGEMM__64
#define SGEMV  SGEMV__64
#define SGER   SGER__64
#define SROT   SROT__64
#define SROTG  SROTG__64
#define SSCAL  SSCAL__64
#define SSWAP  SSWAP__64
#define SSYMM  SSYMM__64
#define SSYMV  SSYMV__64
#define SSYR   SSYR__64
#define SSYR2  SSYR2__64
#define SSYR2K SSYR2K__64
#define SSYRK  SSYRK__64
#define STBSV  STBSV__64
#define STPMV  STPMV__64
#define STPSV  STPSV__64
#define STRMM  STRMM__64
#define STRMV  STRMV__64
#define STRSM  STRSM__64
#define STRSV  STRSV__64
#define XERBLA XERBLA__64
#define ZCOPY  ZCOPY__64
#define ZDSCAL ZDSCAL__64
#define ZGEMM  ZGEMM__64
#define ZGEMV  ZGEMV__64
#define ZGERC  ZGERC__64
#define ZGERU  ZGERU__64
#define ZHER   ZHER__64
#define ZSCAL  ZSCAL__64
#define ZSWAP  ZSWAP__64
#define ZTRMM  ZTRMM__64
#define ZTRMV  ZTRMV__64
#define ZTRSM  ZTRSM__64
#elif GALAHAD_NO_SYMBOL_64BIT_INTEGER
#define DASUM  DASUM
#define DCABS1 DCABS1
#define DDOT   DDOT
#define DNRM2  DNRM2
#define DZNRM2 DZNRM2
#define LSAME  LSAME
#define SASUM  SASUM
#define SDOT   SDOT
#define SNRM2  SNRM2
#define DAXPY  DAXPY
#define DCOPY  DCOPY
#define DGEMM  DGEMM
#define DGEMV  DGEMV
#define DGER   DGER
#define DROT   DROT
#define DROTG  DROTG
#define DSCAL  DSCAL
#define DSWAP  DSWAP
#define DSYMM  DSYMM
#define DSYMV  DSYMV
#define DSYR   DSYR
#define DSYR2  DSYR2
#define DSYR2K DSYR2K
#define DSYRK  DSYRK
#define DTBSV  DTBSV
#define DTPMV  DTPMV
#define DTPSV  DTPSV
#define DTRMM  DTRMM
#define DTRMV  DTRMV
#define DTRSM  DTRSM
#define DTRSV  DTRSV
#define SAXPY  SAXPY
#define SCOPY  SCOPY
#define SGEMM  SGEMM
#define SGEMV  SGEMV
#define SGER   SGER
#define SROT   SROT
#define SROTG  SROTG
#define SSCAL  SSCAL
#define SSWAP  SSWAP
#define SSYMM  SSYMM
#define SSYMV  SSYMV
#define SSYR   SSYR
#define SSYR2  SSYR2
#define SSYR2K SSYR2K
#define SSYRK  SSYRK
#define STBSV  STBSV
#define STPMV  STPMV
#define STPSV  STPSV
#define STRMM  STRMM
#define STRMV  STRMV
#define STRSM  STRSM
#define STRSV  STRSV
#define XERBLA XERBLA
#define ZCOPY  ZCOPY
#define ZDSCAL ZDSCAL
#define ZGEMM  ZGEMM
#define ZGEMV  ZGEMV
#define ZGERC  ZGERC
#define ZGERU  ZGERU
#define ZHER   ZHER
#define ZSCAL  ZSCAL
#define ZSWAP  ZSWAP
#define ZTRMM  ZTRMM
#define ZTRMV  ZTRMV
#define ZTRSM  ZTRSM
#else
#define DASUM  DASUM_64
#define DCABS1 DCABS1_64
#define DDOT   DDOT_64
#define DNRM2  DNRM2_64
#define DZNRM2 DZNRM2_64
#define LSAME  LSAME_64
#define SASUM  SASUM_64
#define SDOT   SDOT_64
#define SNRM2  SNRM2_64
#define DAXPY  DAXPY_64
#define DCOPY  DCOPY_64
#define DGEMM  DGEMM_64
#define DGEMV  DGEMV_64
#define DGER   DGER_64
#define DROT   DROT_64
#define DROTG  DROTG_64
#define DSCAL  DSCAL_64
#define DSWAP  DSWAP_64
#define DSYMM  DSYMM_64
#define DSYMV  DSYMV_64
#define DSYR   DSYR_64
#define DSYR2  DSYR2_64
#define DSYR2K DSYR2K_64
#define DSYRK  DSYRK_64
#define DTBSV  DTBSV_64
#define DTPMV  DTPMV_64
#define DTPSV  DTPSV_64
#define DTRMM  DTRMM_64
#define DTRMV  DTRMV_64
#define DTRSM  DTRSM_64
#define DTRSV  DTRSV_64
#define SAXPY  SAXPY_64
#define SCOPY  SCOPY_64
#define SGEMM  SGEMM_64
#define SGEMV  SGEMV_64
#define SGER   SGER_64
#define SROT   SROT_64
#define SROTG  SROTG_64
#define SSCAL  SSCAL_64
#define SSWAP  SSWAP_64
#define SSYMM  SSYMM_64
#define SSYMV  SSYMV_64
#define SSYR   SSYR_64
#define SSYR2  SSYR2_64
#define SSYR2K SSYR2K_64
#define SSYRK  SSYRK_64
#define STBSV  STBSV_64
#define STPMV  STPMV_64
#define STPSV  STPSV_64
#define STRMM  STRMM_64
#define STRMV  STRMV_64
#define STRSM  STRSM_64
#define STRSV  STRSV_64
#define XERBLA XERBLA_64
#define ZCOPY  ZCOPY_64
#define ZDSCAL ZDSCAL_64
#define ZGEMM  ZGEMM_64
#define ZGEMV  ZGEMV_64
#define ZGERC  ZGERC_64
#define ZGERU  ZGERU_64
#define ZHER   ZHER_64
#define ZSCAL  ZSCAL_64
#define ZSWAP  ZSWAP_64
#define ZTRMM  ZTRMM_64
#define ZTRMV  ZTRMV_64
#define ZTRSM  ZTRSM_64
#endif
#endif
