#ifdef INTEGER_64
#define GALAHAD_SYMBOLS GALAHAD_SYMBOLS_64
#define GALAHAD_KINDS GALAHAD_KINDS_64
#define GALAHAD_HW_TOPOLOGY GALAHAD_HW_TOPOLOGY_64
#define GALAHAD_SSIDS_profile GALAHAD_SSIDS_profile_64
#endif

#ifdef REAL_32
#ifdef INTEGER_64
#define GALAHAD_KINDS_precision GALAHAD_KINDS_single_64
#define GALAHAD_NODEND_precision GALAHAD_NODEND_single_64
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_single_64
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_single_ciface_64
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_single_64
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_single_64
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_sgl_64
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_single_64
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_single_64
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_single_64
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_single_64
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_single_64
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_single_64
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_single_64
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_single_64
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_single_64
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_single_64
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_single_64
#define GALAHAD_MO_precision GALAHAD_MO_single_64
#define GALAHAD_MS_precision GALAHAD_MS_single_64
#define GALAHAD_MU_precision GALAHAD_MU_single_64
#define GALAHAD_RAND_precision GALAHAD_RAND_single_64
#define GALAHAD_RB_precision GALAHAD_RB_single_64
#else
#define GALAHAD_KINDS_precision GALAHAD_KINDS_single
#define GALAHAD_NODEND_precision GALAHAD_NODEND_single
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_single
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_single_ciface
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_single
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_single
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_sgl
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_single
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_single
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_single
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_single
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_single
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_single
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_single
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_single
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_single
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_single
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_single
#define GALAHAD_MO_precision GALAHAD_MO_single
#define GALAHAD_MS_precision GALAHAD_MS_single
#define GALAHAD_MU_precision GALAHAD_MU_single
#define GALAHAD_RAND_precision GALAHAD_RAND_single
#define GALAHAD_RB_precision GALAHAD_RB_single
#endif
#elif REAL_128
#ifdef INTEGER_64
#define GALAHAD_KINDS_precision GALAHAD_KINDS_quadruple_64
#define GALAHAD_NODEND_precision GALAHAD_NODEND_quadruple_64
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_quadruple_64
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_quadruple_ciface_64
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_quadruple_64
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_quadruple_64
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_qul_64
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_quadruple_64
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_quadruple_64
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_quadruple_64
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_quadruple_64
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_quadruple_64
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_quadruple_64
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_quadruple_64
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_quadruple_64
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_quadruple_64
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_quadruple_64
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_quadruple_64
#define GALAHAD_MO_precision GALAHAD_MO_quadruple_64
#define GALAHAD_MS_precision GALAHAD_MS_quadruple_64
#define GALAHAD_MU_precision GALAHAD_MU_quadruple_64
#define GALAHAD_RAND_precision GALAHAD_RAND_quadruple_64
#define GALAHAD_RB_precision GALAHAD_RB_quadruple_64
#else
#define GALAHAD_KINDS_precision GALAHAD_KINDS_quadruple
#define GALAHAD_NODEND_precision GALAHAD_NODEND_quadruple
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_quadruple
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_quadruple_ciface
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_quadruple
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_quadruple
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_qul
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_quadruple
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_quadruple
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_quadruple
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_quadruple
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_quadruple
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_quadruple
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_quadruple
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_quadruple
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_quadruple
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_quadruple
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_quadruple
#define GALAHAD_MO_precision GALAHAD_MO_quadruple
#define GALAHAD_MS_precision GALAHAD_MS_quadruple
#define GALAHAD_MU_precision GALAHAD_MU_quadruple
#define GALAHAD_RAND_precision GALAHAD_RAND_quadruple
#define GALAHAD_RB_precision GALAHAD_RB_quadruple
#endif
#else
#ifdef INTEGER_64
#define GALAHAD_KINDS_precision GALAHAD_KINDS_double_64
#define GALAHAD_NODEND_precision GALAHAD_NODEND_double_64
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_double_64
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_double_ciface_64
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_double_64
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_double_64
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_dbl_64
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_double_64
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_double_64
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_double_64
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_double_64
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_double_64
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_double_64
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_double_64
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_double_64
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_double_64
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_double_64
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_double_64
#define GALAHAD_MO_precision GALAHAD_MO_double_64
#define GALAHAD_MS_precision GALAHAD_MS_double_64
#define GALAHAD_MU_precision GALAHAD_MU_double_64
#define GALAHAD_RAND_precision GALAHAD_RAND_double_64
#define GALAHAD_RB_precision GALAHAD_RB_double_64
#else
#define GALAHAD_KINDS_precision GALAHAD_KINDS_double
#define GALAHAD_NODEND_precision GALAHAD_NODEND_double
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_double
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_double_ciface
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_double
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_double
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_dbl
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_double
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_double
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_double
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_double
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_double
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_double
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_double
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_double
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_double
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_double
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_double
#define GALAHAD_MO_precision GALAHAD_MO_double
#define GALAHAD_MS_precision GALAHAD_MS_double
#define GALAHAD_MU_precision GALAHAD_MU_double
#define GALAHAD_RAND_precision GALAHAD_RAND_double
#define GALAHAD_RB_precision GALAHAD_RB_double
#endif
#endif

