#ifdef INTEGER_64
#define GALAHAD_SYMBOLS GALAHAD_SYMBOLS_64
#define GALAHAD_KINDS GALAHAD_KINDS_64
#define GALAHAD_HW_TOPOLOGY GALAHAD_HW_TOPOLOGY_64
#define GALAHAD_SSIDS_profile GALAHAD_SSIDS_profile_64
#endif

#ifdef REAL_32
#ifdef INTEGER_64
#define GALAHAD_KINDS_precision GALAHAD_KINDS_single_64
#define GALAHAD_NODEND_precision GALAHAD_NODEND_single_64
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_single_64
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_single_ciface_64
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_single_64
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_single_64
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_sgl_64
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_single_64
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_single_64
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_single_64
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_single_64
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_single_64
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_single_64
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_single_64
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_single_64
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_single_64
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_single_64
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_single_64
#define SPRAL_MATCH_ORDER_precision SPRAL_MATCH_ORDER_single_64
#define SPRAL_MATRIX_UTIL_precision SPRAL_MATRIX_UTIL_single_64
#define SPRAL_RAL_BOEING_precision SPRAL_RAL_BOEING_single_64
#define SPRAL_SCALING_precision SPRAL_SCALING_single_64
#else
#define GALAHAD_KINDS_precision GALAHAD_KINDS_single
#define GALAHAD_NODEND_precision GALAHAD_NODEND_single
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_single
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_single_ciface
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_single
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_single
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_sgl
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_single
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_single
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_single
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_single
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_single
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_single
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_single
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_single
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_single
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_single
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_single
#define SPRAL_MATCH_ORDER_precision SPRAL_MATCH_ORDER_single
#define SPRAL_MATRIX_UTIL_precision SPRAL_MATRIX_UTIL_single
#define SPRAL_RAL_BOEING_precision SPRAL_RAL_BOEING_single
#define SPRAL_SCALING_precision SPRAL_SCALING_single
#endif
#elif REAL_128
#ifdef INTEGER_64
#define GALAHAD_KINDS_precision GALAHAD_KINDS_quadruple_64
#define GALAHAD_NODEND_precision GALAHAD_NODEND_quadruple_64
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_quadruple_64
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_quadruple_ciface_64
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_quadruple_64
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_quadruple_64
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_qul_64
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_quadruple_64
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_quadruple_64
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_quadruple_64
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_quadruple_64
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_quadruple_64
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_quadruple_64
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_quadruple_64
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_quadruple_64
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_quadruple_64
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_quadruple_64
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_quadruple_64
#define SPRAL_MATCH_ORDER_precision SPRAL_MATCH_ORDER_quadruple_64
#define SPRAL_MATRIX_UTIL_precision SPRAL_MATRIX_UTIL_quadruple_64
#define SPRAL_RAL_BOEING_precision SPRAL_RAL_BOEING_quadruple_64
#define SPRAL_SCALING_precision SPRAL_SCALING_quadruple_64
#else
#define GALAHAD_KINDS_precision GALAHAD_KINDS_quadruple
#define GALAHAD_NODEND_precision GALAHAD_NODEND_quadruple
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_quadruple
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_quadruple_ciface
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_quadruple
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_quadruple
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_qul
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_quadruple
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_quadruple
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_quadruple
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_quadruple
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_quadruple
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_quadruple
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_quadruple
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_quadruple
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_quadruple
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_quadruple
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_quadruple
#define SPRAL_MATCH_ORDER_precision SPRAL_MATCH_ORDER_quadruple
#define SPRAL_MATRIX_UTIL_precision SPRAL_MATRIX_UTIL_quadruple
#define SPRAL_RAL_BOEING_precision SPRAL_RAL_BOEING_quadruple
#define SPRAL_SCALING_precision SPRAL_SCALING_quadruple
#endif
#else
#ifdef INTEGER_64
#define GALAHAD_KINDS_precision GALAHAD_KINDS_double_64
#define GALAHAD_NODEND_precision GALAHAD_NODEND_double_64
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_double_64
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_double_ciface_64
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_double_64
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_double_64
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_dbl_64
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_double_64
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_double_64
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_double_64
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_double_64
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_double_64
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_double_64
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_double_64
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_double_64
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_double_64
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_double_64
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_double_64
#define SPRAL_MATCH_ORDER_precision SPRAL_MATCH_ORDER_double_64
#define SPRAL_MATRIX_UTIL_precision SPRAL_MATRIX_UTIL_double_64
#define SPRAL_RAL_BOEING_precision SPRAL_RAL_BOEING_double_64
#define SPRAL_SCALING_precision SPRAL_SCALING_double_64
#else
#define GALAHAD_KINDS_precision GALAHAD_KINDS_double
#define GALAHAD_NODEND_precision GALAHAD_NODEND_double
#define GALAHAD_SSIDS_precision GALAHAD_SSIDS_double
#define GALAHAD_SSIDS_precision_ciface GALAHAD_SSIDS_double_ciface
#define GALAHAD_SSIDS_akeep_precision GALAHAD_SSIDS_akeep_double
#define GALAHAD_SSIDS_analyse_precision GALAHAD_SSIDS_analyse_double
#define GALAHAD_SSIDS_contrib_free_precision GALAHAD_SSIDS_contrib_free_dbl
#define GALAHAD_SSIDS_contrib_fsub_precision GALAHAD_SSIDS_contrib_fsub_double
#define GALAHAD_SSIDS_contrib_precision GALAHAD_SSIDS_contrib_double
#define GALAHAD_SSIDS_contrib_get_data_precision GALAHAD_SSIDS_contrib_get_data_double
#define GALAHAD_SSIDS_cpu_iface_precision GALAHAD_SSIDS_cpu_iface_double
#define GALAHAD_SSIDS_cpu_subtree_precision GALAHAD_SSIDS_cpu_subtree_double
#define GALAHAD_SSIDS_fkeep_precision GALAHAD_SSIDS_fkeep_double
#define GALAHAD_SSIDS_gpu_subtree_precision GALAHAD_SSIDS_gpu_subtree_double
#define GALAHAD_SSIDS_inform_precision GALAHAD_SSIDS_inform_double
#define GALAHAD_SSIDS_profile_precision GALAHAD_SSIDS_profile_double
#define GALAHAD_SSIDS_subtree_precision GALAHAD_SSIDS_subtree_double
#define GALAHAD_SSIDS_types_precision GALAHAD_SSIDS_types_double
#define SPRAL_MATCH_ORDER_precision SPRAL_MATCH_ORDER_double
#define SPRAL_MATRIX_UTIL_precision SPRAL_MATRIX_UTIL_double
#define SPRAL_RAL_BOEING_precision SPRAL_RAL_BOEING_double
#define SPRAL_SCALING_precision SPRAL_SCALING_double
#endif
#endif

