#ifdef INTEGER_64
#ifdef REAL_32
#define ldlt_app_factor ldlt_app_factor_sgl_64
#define ldlt_app_solve_fwd ldlt_app_solve_fwd_sgl_64
#define ldlt_app_solve_diag ldlt_app_solve_diag_sgl_64
#define ldlt_app_solve_bwd ldlt_app_solve_bwd_sgl_64
#define ldlt_tpp_factor ldlt_tpp_factor_sgl_64
#define ldlt_tpp_solve_fwd ldlt_tpp_solve_fwd_sgl_64
#define ldlt_tpp_solve_diag ldlt_tpp_solve_diag_sgl_64
#define ldlt_tpp_solve_bwd ldlt_tpp_solve_bwd_sgl_64
#define ldlt_nopiv_factor ldlt_nopiv_factor_sgl_64
#define ldlt_nopiv_solve_fwd ldlt_nopiv_solve_fwd_sgl_64
#define ldlt_nopiv_solve_diag ldlt_nopiv_solve_diag_sgl_64
#define ldlt_nopiv_solve_bwd ldlt_nopiv_solve_bwd_sgl_64
#define cholesky_factor cholesky_factor_sgl_64
#define cholesky_solve_fwd cholesky_solve_fwd_sgl_64
#define cholesky_solve_bwd cholesky_solve_bwd_sgl_64
#define spral_ssids_contrib_get_data spral_ssids_contrib_get_data_single_64
#define spral_ssids_contrib_free spral_ssids_contrib_free_sgl_64
#define FAPrecisionTraits FASingleTraits_64
#define factor_alloc_precision factor_alloc_single_64
#define spral_ssids_cpu_create_num_subtree spral_ssids_cpu_create_num_subtree_sgl_64
#define spral_ssids_cpu_destroy_num_subtree spral_ssids_cpu_destroy_num_subtree_sgl_64
#define spral_ssids_cpu_subtree_solve_fwd spral_ssids_cpu_subtree_solve_fwd_sgl_64
#define spral_ssids_cpu_subtree_solve_diag spral_ssids_cpu_subtree_solve_diag_sgl_64
#define spral_ssids_cpu_subtree_solve_diag_bwd spral_ssids_cpu_subtree_solve_diag_bwd_sgl_64
#define spral_ssids_cpu_subtree_solve_bwd spral_ssids_cpu_subtree_solve_bwd_sgl_64
#define spral_ssids_cpu_subtree_enquire spral_ssids_cpu_subtree_enquire_sgl_64
#define spral_ssids_cpu_subtree_alter spral_ssids_cpu_subtree_alter_sgl_64
#define spral_ssids_cpu_subtree_get_contrib spral_ssids_cpu_subtree_get_contrib_sgl_64
#define spral_ssids_cpu_subtree_free_contrib spral_ssids_cpu_subtree_free_contrib_sgl_64
#define ldlt_app_internal ldlt_app_internal_sgl_64
#define ldlt_app_factor_mem_required ldlt_app_factor_mem_required_sgl_64
#elif REAL_128
#include <quadmath.h>
#define ldlt_app_factor ldlt_app_factor_qul_64
#define ldlt_app_solve_fwd ldlt_app_solve_fwd_qul_64
#define ldlt_app_solve_diag ldlt_app_solve_diag_qul_64
#define ldlt_app_solve_bwd ldlt_app_solve_bwd_qul_64
#define ldlt_tpp_factor ldlt_tpp_factor_qul_64
#define ldlt_tpp_solve_fwd ldlt_tpp_solve_fwd_qul_64
#define ldlt_tpp_solve_diag ldlt_tpp_solve_diag_qul_64
#define ldlt_tpp_solve_bwd ldlt_tpp_solve_bwd_qul_64
#define ldlt_nopiv_factor ldlt_nopiv_factor_qul_64
#define ldlt_nopiv_solve_fwd ldlt_nopiv_solve_fwd_qul_64
#define ldlt_nopiv_solve_diag ldlt_nopiv_solve_diag_qul_64
#define ldlt_nopiv_solve_bwd ldlt_nopiv_solve_bwd_qul_64
#define cholesky_factor cholesky_factor_qul_64
#define cholesky_solve_fwd cholesky_solve_fwd_qul_64
#define cholesky_solve_bwd cholesky_solve_bwd_qul_64
#define spral_ssids_contrib_get_data spral_ssids_contrib_get_data_quadruple_64
#define spral_ssids_contrib_free spral_ssids_contrib_free_qul_64
#define FAPrecisionTraits FAQuadrupleTraits_64
#define factor_alloc_precision factor_alloc_quadruple_64
#define spral_ssids_cpu_create_num_subtree spral_ssids_cpu_create_num_subtree_qul_64
#define spral_ssids_cpu_destroy_num_subtree spral_ssids_cpu_destroy_num_subtree_qul_64
#define spral_ssids_cpu_subtree_solve_fwd spral_ssids_cpu_subtree_solve_fwd_qul_64
#define spral_ssids_cpu_subtree_solve_diag spral_ssids_cpu_subtree_solve_diag_qul_64
#define spral_ssids_cpu_subtree_solve_diag_bwd spral_ssids_cpu_subtree_solve_diag_bwd_qul_64
#define spral_ssids_cpu_subtree_solve_bwd spral_ssids_cpu_subtree_solve_bwd_qul_64
#define spral_ssids_cpu_subtree_enquire spral_ssids_cpu_subtree_enquire_qul_64
#define spral_ssids_cpu_subtree_alter spral_ssids_cpu_subtree_alter_qul_64
#define spral_ssids_cpu_subtree_get_contrib spral_ssids_cpu_subtree_get_contrib_qul_64
#define spral_ssids_cpu_subtree_free_contrib spral_ssids_cpu_subtree_free_contrib_qul_64
#define ldlt_app_internal ldlt_app_internal_qul_64
#define ldlt_app_factor_mem_required ldlt_app_factor_mem_required_qul_64
#else
#define ldlt_app_factor ldlt_app_factor_dbl_64
#define ldlt_app_solve_fwd ldlt_app_solve_fwd_dbl_64
#define ldlt_app_solve_diag ldlt_app_solve_diag_dbl_64
#define ldlt_app_solve_bwd ldlt_app_solve_bwd_dbl_64
#define ldlt_tpp_factor ldlt_tpp_factor_dbl_64
#define ldlt_tpp_solve_fwd ldlt_tpp_solve_fwd_dbl_64
#define ldlt_tpp_solve_diag ldlt_tpp_solve_diag_dbl_64
#define ldlt_tpp_solve_bwd ldlt_tpp_solve_bwd_dbl_64
#define ldlt_nopiv_factor ldlt_nopiv_factor_dbl_64
#define ldlt_nopiv_solve_fwd ldlt_nopiv_solve_fwd_dbl_64
#define ldlt_nopiv_solve_diag ldlt_nopiv_solve_diag_dbl_64
#define ldlt_nopiv_solve_bwd ldlt_nopiv_solve_bwd_dbl_64
#define cholesky_factor cholesky_factor_dbl_64
#define cholesky_solve_fwd cholesky_solve_fwd_dbl_64
#define cholesky_solve_bwd cholesky_solve_bwd_dbl_64
#define spral_ssids_contrib_get_data spral_ssids_contrib_get_data_double_64
#define spral_ssids_contrib_free spral_ssids_contrib_free_dbl_64
#define FAPrecisionTraits FADoubleTraits_64
#define factor_alloc_precision factor_alloc_double_64
#define spral_ssids_cpu_create_num_subtree spral_ssids_cpu_create_num_subtree_dbl_64
#define spral_ssids_cpu_destroy_num_subtree spral_ssids_cpu_destroy_num_subtree_dbl_64
#define spral_ssids_cpu_subtree_solve_fwd spral_ssids_cpu_subtree_solve_fwd_dbl_64
#define spral_ssids_cpu_subtree_solve_diag spral_ssids_cpu_subtree_solve_diag_dbl_64
#define spral_ssids_cpu_subtree_solve_diag_bwd spral_ssids_cpu_subtree_solve_diag_bwd_dbl_64
#define spral_ssids_cpu_subtree_solve_bwd spral_ssids_cpu_subtree_solve_bwd_dbl_64
#define spral_ssids_cpu_subtree_enquire spral_ssids_cpu_subtree_enquire_dbl_64
#define spral_ssids_cpu_subtree_alter spral_ssids_cpu_subtree_alter_dbl_64
#define spral_ssids_cpu_subtree_get_contrib spral_ssids_cpu_subtree_get_contrib_dbl_64
#define spral_ssids_cpu_subtree_free_contrib spral_ssids_cpu_subtree_free_contrib_dbl_64
#define ldlt_app_internal ldlt_app_internal_dbl_64
#define ldlt_app_factor_mem_required ldlt_app_factor_mem_required_dbl_64
#endif
#else
#ifdef REAL_32
#define ldlt_app_factor ldlt_app_factor_sgl
#define ldlt_app_solve_fwd ldlt_app_solve_fwd_sgl
#define ldlt_app_solve_diag ldlt_app_solve_diag_sgl
#define ldlt_app_solve_bwd ldlt_app_solve_bwd_sgl
#define ldlt_tpp_factor ldlt_tpp_factor_sgl
#define ldlt_tpp_solve_fwd ldlt_tpp_solve_fwd_sgl
#define ldlt_tpp_solve_diag ldlt_tpp_solve_diag_sgl
#define ldlt_tpp_solve_bwd ldlt_tpp_solve_bwd_sgl
#define ldlt_nopiv_factor ldlt_nopiv_factor_sgl
#define ldlt_nopiv_solve_fwd ldlt_nopiv_solve_fwd_sgl
#define ldlt_nopiv_solve_diag ldlt_nopiv_solve_diag_sgl
#define ldlt_nopiv_solve_bwd ldlt_nopiv_solve_bwd_sgl
#define cholesky_factor cholesky_factor_sgl
#define cholesky_solve_fwd cholesky_solve_fwd_sgl
#define cholesky_solve_bwd cholesky_solve_bwd_sgl
#define spral_ssids_contrib_get_data spral_ssids_contrib_get_data_single
#define spral_ssids_contrib_free spral_ssids_contrib_free_sgl
#define FAPrecisionTraits FASingleTraits
#define factor_alloc_precision factor_alloc_single
#define spral_ssids_cpu_create_num_subtree spral_ssids_cpu_create_num_subtree_sgl
#define spral_ssids_cpu_destroy_num_subtree spral_ssids_cpu_destroy_num_subtree_sgl
#define spral_ssids_cpu_subtree_solve_fwd spral_ssids_cpu_subtree_solve_fwd_sgl
#define spral_ssids_cpu_subtree_solve_diag spral_ssids_cpu_subtree_solve_diag_sgl
#define spral_ssids_cpu_subtree_solve_diag_bwd spral_ssids_cpu_subtree_solve_diag_bwd_sgl
#define spral_ssids_cpu_subtree_solve_bwd spral_ssids_cpu_subtree_solve_bwd_sgl
#define spral_ssids_cpu_subtree_enquire spral_ssids_cpu_subtree_enquire_sgl
#define spral_ssids_cpu_subtree_alter spral_ssids_cpu_subtree_alter_sgl
#define spral_ssids_cpu_subtree_get_contrib spral_ssids_cpu_subtree_get_contrib_sgl
#define spral_ssids_cpu_subtree_free_contrib spral_ssids_cpu_subtree_free_contrib_sgl
#define ldlt_app_internal ldlt_app_internal_sgl
#define ldlt_app_factor_mem_required ldlt_app_factor_mem_required_sgl
#elif REAL_128
#include <quadmath.h>
#define ldlt_app_factor ldlt_app_factor_qul
#define ldlt_app_solve_fwd ldlt_app_solve_fwd_qul
#define ldlt_app_solve_diag ldlt_app_solve_diag_qul
#define ldlt_app_solve_bwd ldlt_app_solve_bwd_qul
#define ldlt_tpp_factor ldlt_tpp_factor_qul
#define ldlt_tpp_solve_fwd ldlt_tpp_solve_fwd_qul
#define ldlt_tpp_solve_diag ldlt_tpp_solve_diag_qul
#define ldlt_tpp_solve_bwd ldlt_tpp_solve_bwd_qul
#define ldlt_nopiv_factor ldlt_nopiv_factor_qul
#define ldlt_nopiv_solve_fwd ldlt_nopiv_solve_fwd_qul
#define ldlt_nopiv_solve_diag ldlt_nopiv_solve_diag_qul
#define ldlt_nopiv_solve_bwd ldlt_nopiv_solve_bwd_qul
#define cholesky_factor cholesky_factor_qul
#define cholesky_solve_fwd cholesky_solve_fwd_qul
#define cholesky_solve_bwd cholesky_solve_bwd_qul
#define spral_ssids_contrib_get_data spral_ssids_contrib_get_data_quadruple
#define spral_ssids_contrib_free spral_ssids_contrib_free_qul
#define FAPrecisionTraits FAQuadrupleTraits
#define factor_alloc_precision factor_alloc_quadruple
#define spral_ssids_cpu_create_num_subtree spral_ssids_cpu_create_num_subtree_qul
#define spral_ssids_cpu_destroy_num_subtree spral_ssids_cpu_destroy_num_subtree_qul
#define spral_ssids_cpu_subtree_solve_fwd spral_ssids_cpu_subtree_solve_fwd_qul
#define spral_ssids_cpu_subtree_solve_diag spral_ssids_cpu_subtree_solve_diag_qul
#define spral_ssids_cpu_subtree_solve_diag_bwd spral_ssids_cpu_subtree_solve_diag_bwd_qul
#define spral_ssids_cpu_subtree_solve_bwd spral_ssids_cpu_subtree_solve_bwd_qul
#define spral_ssids_cpu_subtree_enquire spral_ssids_cpu_subtree_enquire_qul
#define spral_ssids_cpu_subtree_alter spral_ssids_cpu_subtree_alter_qul
#define spral_ssids_cpu_subtree_get_contrib spral_ssids_cpu_subtree_get_contrib_qul
#define spral_ssids_cpu_subtree_free_contrib spral_ssids_cpu_subtree_free_contrib_qul
#define ldlt_app_internal ldlt_app_internal_qul
#define ldlt_app_factor_mem_required ldlt_app_factor_mem_required_qul
#else
#define ldlt_app_factor ldlt_app_factor_dbl
#define ldlt_app_solve_fwd ldlt_app_solve_fwd_dbl
#define ldlt_app_solve_diag ldlt_app_solve_diag_dbl
#define ldlt_app_solve_bwd ldlt_app_solve_bwd_dbl
#define ldlt_tpp_factor ldlt_tpp_factor_dbl
#define ldlt_tpp_solve_fwd ldlt_tpp_solve_fwd_dbl
#define ldlt_tpp_solve_diag ldlt_tpp_solve_diag_dbl
#define ldlt_tpp_solve_bwd ldlt_tpp_solve_bwd_dbl
#define ldlt_nopiv_factor ldlt_nopiv_factor_dbl
#define ldlt_nopiv_solve_fwd ldlt_nopiv_solve_fwd_dbl
#define ldlt_nopiv_solve_diag ldlt_nopiv_solve_diag_dbl
#define ldlt_nopiv_solve_bwd ldlt_nopiv_solve_bwd_dbl
#define cholesky_factor cholesky_factor_dbl
#define cholesky_solve_fwd cholesky_solve_fwd_dbl
#define cholesky_solve_bwd cholesky_solve_bwd_dbl
#define spral_ssids_contrib_get_data spral_ssids_contrib_get_data_double
#define spral_ssids_contrib_free spral_ssids_contrib_free_dbl
#define FAPrecisionTraits FADoubleTraits
#define factor_alloc_precision factor_alloc_double
#define spral_ssids_cpu_create_num_subtree spral_ssids_cpu_create_num_subtree_dbl
#define spral_ssids_cpu_destroy_num_subtree spral_ssids_cpu_destroy_num_subtree_dbl
#define spral_ssids_cpu_subtree_solve_fwd spral_ssids_cpu_subtree_solve_fwd_dbl
#define spral_ssids_cpu_subtree_solve_diag spral_ssids_cpu_subtree_solve_diag_dbl
#define spral_ssids_cpu_subtree_solve_diag_bwd spral_ssids_cpu_subtree_solve_diag_bwd_dbl
#define spral_ssids_cpu_subtree_solve_bwd spral_ssids_cpu_subtree_solve_bwd_dbl
#define spral_ssids_cpu_subtree_enquire spral_ssids_cpu_subtree_enquire_dbl
#define spral_ssids_cpu_subtree_alter spral_ssids_cpu_subtree_alter_dbl
#define spral_ssids_cpu_subtree_get_contrib spral_ssids_cpu_subtree_get_contrib_dbl
#define spral_ssids_cpu_subtree_free_contrib spral_ssids_cpu_subtree_free_contrib_dbl
#define ldlt_app_internal ldlt_app_internal_dbl
#define ldlt_app_factor_mem_required ldlt_app_factor_mem_required_dbl
#endif
#endif

#ifdef INTEGER_64
#define host_gemm host_gemm_64
#define lapack_potrf lapack_potrf_64
#define host_syrk host_syrk_64
#define host_trsv host_trsv_64
#define host_trsm host_trsm_64
#define gemv gemv_64
#endif

#ifdef GALAHAD_BLAS
#ifdef REAL_32
#ifdef INTEGER_64
#define trsm galahad_strsm_64
#define trsv galahad_strsv_64
#define gemm galahad_sgemm_64
#define gemv galahad_sgemv_64
#else
#define trsm galahad_strsm
#define trsv galahad_strsv
#define gemm galahad_sgemm
#define gemv galahad_sgemv
#endif
#elif REAL_128
#ifdef INTEGER_64
#define trsm galahad_qtrsm_64
#define trsv galahad_qtrsv_64
#define gemm galahad_qgemm_64
#define gemv galahad_qgemv_64
#else
#define trsm galahad_qtrsm
#define trsv galahad_qtrsv
#define gemm galahad_qgemm
#define gemv galahad_qgemv
#endif
#else
#ifdef INTEGER_64
#define trsm galahad_dtrsm_64
#define trsv galahad_dtrsv_64
#define gemm galahad_dgemm_64
#define gemv galahad_dgemv_64
#else
#define trsm galahad_dtrsm
#define trsv galahad_dtrsv
#define gemm galahad_dgemm
#define gemv galahad_dgemv
#endif
#endif
#else
#ifdef REAL_32
#ifdef INTEGER_64
#define trsm strsm_64
#define trsv strsv_64
#define gemm sgemm_64
#define gemv sgemv_64
#else
#define trsm strsm
#define trsv strsv
#define gemm sgemm
#define gemv sgemv
#endif
#elif REAL_128
#ifdef INTEGER_64
#define trsm qtrsm_64
#define trsv qtrsv_64
#define gemm qgemm_64
#define gemv qgemv_64
#else
#define trsm qtrsm
#define trsv qtrsv
#define gemm qgemm
#define gemv qgemv
#endif
#else
#ifdef INTEGER_64
#define trsm dtrsm_64
#define trsv dtrsv_64
#define gemm dgemm_64
#define gemv dgemv_64
#else
#define trsm dtrsm
#define trsv dtrsv
#define gemm dgemm
#define gemv dgemv
#endif
#endif
#endif

/*
#ifdef INTEGER_64
#define SymbolicSubtree SymbolicSubtree_64
#define SmallLeafSymbolicSubtree SmallLeafSymbolicSubtree_64
#define SmallLeafNumericSubtree SmallLeafNumericSubtree_64
#define SymbolicNode SymbolicNode_64
#define BuddyAllocator BuddyAllocator_64
#define Page Page_64
#define Table Table_64
#define NumericSubtree NumericSubtree_64
#define now now_64
#define end end_64
#define guess_core guess_core_64
#define Task Task_64
#define setState setState_64
#define Workspace Workspace_64
#define ThreadStats ThreadStats_64
#define SingularError SingularError_64
#define SymbolicSubtree SymbolicSubtree_64
#define NumericSubtree NumericSubtree_64
#define SymbolicNode SymbolicNode_64
#define NumericNode NumericNode_64
#define AppendAlloc AppendAlloc_64
#define Page Page_64
#define Pool Pool_64
#endif
*/

#ifdef REAL_32
#ifdef INTEGER_64
#define spral_c_gemv  spral_c_sgemv_64
#define spral_c_trsv  spral_c_strsv_64
#define spral_c_syrk  spral_c_ssyrk_64
#define spral_c_trsm  spral_c_strsm_64
#define spral_c_sytrf spral_c_ssytrf_64
#define spral_c_potrf spral_c_spotrf_64
#define spral_c_gemm  spral_c_sgemm_64
#define GALAHAD_BLAS_inter_precision GALAHAD_BLAS_inter_single_64
#define GALAHAD_LAPACK_inter_precision GALAHAD_LAPACK_inter_single_64
#else
#define spral_c_gemv  spral_c_sgemv
#define spral_c_trsv  spral_c_strsv
#define spral_c_syrk  spral_c_ssyrk
#define spral_c_trsm  spral_c_strsm
#define spral_c_sytrf spral_c_ssytrf
#define spral_c_potrf spral_c_spotrf
#define spral_c_gemm  spral_c_sgemm
#define GALAHAD_BLAS_inter_precision GALAHAD_BLAS_inter_single
#define GALAHAD_LAPACK_inter_precision GALAHAD_LAPACK_inter_single
#endif
#elif REAL_128
#ifdef INTEGER_64
#define spral_c_gemv  spral_c_qgemv_64
#define spral_c_trsv  spral_c_qtrsv_64
#define spral_c_syrk  spral_c_qsyrk_64
#define spral_c_trsm  spral_c_qtrsm_64
#define spral_c_sytrf spral_c_qsytrf_64
#define spral_c_potrf spral_c_qpotrf_64
#define spral_c_gemm  spral_c_qgemm_64
#define GALAHAD_BLAS_inter_precision GALAHAD_BLAS_inter_quadruple_64
#define GALAHAD_LAPACK_inter_precision GALAHAD_LAPACK_inter_quadruple_64
#else
#define spral_c_gemv  spral_c_qgemv
#define spral_c_trsv  spral_c_qtrsv
#define spral_c_syrk  spral_c_qsyrk
#define spral_c_trsm  spral_c_qtrsm
#define spral_c_sytrf spral_c_qsytrf
#define spral_c_potrf spral_c_qpotrf
#define spral_c_gemm  spral_c_qgemm
#define GALAHAD_BLAS_inter_precision GALAHAD_BLAS_inter_quadruple
#define GALAHAD_LAPACK_inter_precision GALAHAD_LAPACK_inter_quadruple
#endif
#else
#ifdef INTEGER_64
#define spral_c_gemv  spral_c_dgemv_64
#define spral_c_trsv  spral_c_dtrsv_64
#define spral_c_syrk  spral_c_dsyrk_64
#define spral_c_trsm  spral_c_dtrsm_64
#define spral_c_sytrf spral_c_dsytrf_64
#define spral_c_potrf spral_c_dpotrf_64
#define spral_c_gemm  spral_c_dgemm_64
#define GALAHAD_BLAS_inter_precision GALAHAD_BLAS_inter_double_64
#define GALAHAD_LAPACK_inter_precision GALAHAD_LAPACK_inter_double_64
#else
#define spral_c_gemv  spral_c_dgemv
#define spral_c_trsv  spral_c_dtrsv
#define spral_c_syrk  spral_c_dsyrk
#define spral_c_trsm  spral_c_dtrsm
#define spral_c_sytrf spral_c_dsytrf
#define spral_c_potrf spral_c_dpotrf
#define spral_c_gemm  spral_c_dgemm
#define GALAHAD_BLAS_inter_precision GALAHAD_BLAS_inter_double
#define GALAHAD_LAPACK_inter_precision GALAHAD_LAPACK_inter_double
#endif
#endif
