.TH gal 1
.SH NAME
\fBgal\fR \- Run a GALAHAD package on the result of a previously-decoded
SIF file
.SH USAGE
.B gal architecture package
[options]
,

where
.B architecture
is a string of the form machine.os.compiler
indicating the machine/operating system/compiler combination to be used and
.B package
indicates the package required.

The name
.B architecture
must match that of one of the files in the directory
$GALAHAD/bin/sys , while
.B package
may be one of
.LP
.TP 1i
.BI lancelot
LANCELOT B for general nonlinear programming
.TP
.BI filtrane
FILTRANE for nonlinear equations/inequlaities and nonlinear least-squares
.TP
.BI presolve
PRESOLVE for presolving general linear or quadratic programs
.TP
.BI qp
QP for general quadratic programming
.TP
.BI qpa
QPA for general quadratic programming using an active-set method
.TP
.BI qpb
QPB for general quadratic programming using an interior-point method
.TP
.BI qpc
QPC for general quadratic programming using a cross-over method
.TP
.BI cqp
CQP for convex quadratic programming using an interior-point method
.TP
.BI dqp
DQP for convex quadratic programming using an dual projection method
.TP
.BI ccqp
CCQP for convex quadratic programming using a cross-over method
.TP
.BI l1qp
L1QP for convex l_1 quadratic programming using a cross-over method
.TP
.BI eqp
EQP for equality-constrained quadratic programming
.TP
.BI bqp
BQP for bound-constrained quadratic programming using a projection method
.TP
.BI bqpb
BQPB for bound-constrained quadratic programming using an interior-point method
.TP
.BI wcp
WCP for well-centered feasible points of a polyhedral region
.TP
.BI trs
TRS for the trust-region subproblem
.TP
.BI rqs
RQS for the regularized quadratic subproblem
.TP
.BI dps
RQS for the diagonilising norm trust-region and regularized quadratic subproblems
.TP
.BI tru
TRU for unconstrained optimization using a trust-region method
.TP
.BI arc
ARC for unconstrained optimization using a regularization method

Other packages will be available in due course.

.SH DESCRIPTION
.LP
.B gal
runs one of the GALAHAD large-scale nonlinear-optimization
package on the result of a previously decoded
user-defined SIF file.
.SH OPTIONS
.LP
.TP 1i
.BI \-e
Use the load module
.BI architecture.package
if it exits. The default is to create a new load module.
.TP
.B \-h
Print a list of these options and stop execution.
.TP
.BI \-r
Do not recompile the object files for the problem. The default is to recompile
existing problem source files.
.TP
.BI \-u
Update the option specification file to incorporate the latest options.
The default is to leave the file alone (and create it if it does not exist).
.TP
.BI \-s
Run the single precision version of the package. The default is
to run the double precision version.
.TP
.B \-k
Keep the load module after use so that the problem may be rerun without further
compilation. The default is to delete the load module after use.
.TP
.B \-m
Check for memory leaks (if possible).
.TP
.B \-p
Profile the code (if possible).
.TP
.BI \-o " output"
Specify the
.IR output
level, which must be one of
.B 0
(no output; the default)
.B 1
(a brief description of the steps performed)
.TP
.BI \-l " secs"
Set a limit of
.IR secs
seconds on the GALAHAD run. The default is 99999999 seconds.
.SH FILES
.TP 20
.BI architecture.package
executable output file created by gal
.TP
.IB RUN package .SPC
user-supplied option specification file
.TP
.IB OUTSDIF.d
file containing problem structure previously created by sdgal
.TP
.IB AUTOMAT.d
file indicating derivative mode
previously created by sdgal
.TP
.IB SAVEDATA.d
file containing intermediate solution created by gal
.TP
.IB SOLUTION.d
file containing solution created by gal
.TP
.IB SUMMARY.d
file containing summary of solution created by gal
.TP
.IB file.f
Fixed-form Fortran 90 or FORTRAN 77 source decoded from the SIF file
previously created by sdgal
.TP
.IB file.f90
Free-form Fortran 90 source decoded from the SIF file
previously created by sdgal
.TP
.IB file.o
object file created by gal
.SH DIAGNOSTICS
The diagnostics produced by gal itself are intended to be self-explanatory.
.SH "SEE ALSO"

N. I. M. Gould, D. Orban and Ph. L. Toint,
"GALAHAD - a library of thread-safe fortran 90 packages for large-scale
nonlinear optimization",
.I ACM Transactions on Mathematic Software
.B 29
(4)
(2003) 353-372.

A. R. Conn, N. I. M. Gould and Ph. L. Toint,
"LANCELOT: a Fortran package for large-scale nonlinear optimization" ,
Springer Series in Computational Mathematics, vol. 17,
Springer Verlag (Heidelberg, New York),
ISBN 3-540-55470-X, 1992.

N. I. M. Gould, S. Leyffer and Ph. L. Toint,
``A multidimensional filter algorithm for nonlinear equations and nonlinear
least-squares",
.I SIAM Journal on Optimization
.B 15
(1)
(2005) 17-38.

N. I. M. Gould and Ph. L. Toint,
"Numerical methods for large-scale non-convex quadratic programming",
in "Trends in Industrial and Applied Mathematics",
(A. Siddiqi and M. Kocvara, eds.),
Kluwer Academic Publishers, Dordrecht, The Netherlands
(2002) 149-179.

N. I. M. Gould and Ph. L. Toint,
"An iterative working-set method for large-scale non-convex quadratic
programming",
.I Applied Numerical Mathematics
.B 43
(1-2)
(2002) 109-128.

A. R. Conn, N. I. M. Gould, D. Orban and Ph. L. Toint,
"A primal-dual trust-region algorithm for non-convex nonlinear optimization".
.I Mathematical Programming ,
.B 87
(2)
(2000) 215-249.

.BR sdgal (1)
.SH BUGS
Please report any bugs found to "nick.gould@rl.ac.uk", along with any
suggestions for improvements.
.SH AUTHORS
Nick Gould, Rutherford Appleton Laboratory,
Dominique Orban, Ecole Polytechnique de Montreal,
and
Philippe Toint, University of Namur
