% test galahad_nls
% Nick Gould for GALAHAD productions 08/March/2019

clear control inform

% NLS documentation problem (dense matrices)

p.m = 2 ;
x0 = [ 1 1 1 ];
[ control ] = galahad_nls( 'initial' );
%control.print_level = 1;
[x, inform ] = galahad_nls( p, x0, 'nls_r', 'nls_j', control );

disp( sprintf( 'Nls: \n%s %13.6e %s %8.4e %s %5.0f %s %4.0f', ...
       ' - final f =', inform.obj, ...
       '- ||g|| =', inform.norm_g, ...
       '- iter =', inform.iter, ...
       '- status =', inform.status ) )

x0 = [ 1 1 1 ];
control.model = 4;
[x, inform ] = galahad_nls( p, x0, 'nls_r', 'nls_j', 'nls_h', control );

disp( sprintf( 'Nls: \n%s %13.6e %s %8.4e %s %5.0f %s %4.0f', ...
       ' - final f =', inform.obj, ...
       '- ||g|| =', inform.norm_g, ...
       '- iter =', inform.iter, ...
       '- status =', inform.status ) )

x0 = [ 1 1 1 ];
control.model = 6;
[x, inform ] = galahad_nls( p, x0, 'nls_r', 'nls_j', 'nls_h', 'nls_p', ...
                            control );

disp( sprintf( 'Nls: \n%s %13.6e %s %8.4e %s %5.0f %s %4.0f', ...
       ' - final f =', inform.obj, ...
       '- ||g|| =', inform.norm_g, ...
       '- iter =', inform.iter, ...
       '- status =', inform.status ) )

% NLS documentation problem (spare matrices)

p.j_row = [ 1 1 2 2 ] ;
p.j_col = [ 1 3 2 3 ] ;

x0 = [ 1 1 1 ];
[ control ] = galahad_nls( 'initial' );
control.model = 3;
[x, inform ] = galahad_nls( p, x0, 'nls_r', 'nls_j_sparse', control );

disp( sprintf( 'Nls: \n%s %13.6e %s %8.4e %s %5.0f %s %4.0f', ...
       ' - final f =', inform.obj, ...
       '- ||g|| =', inform.norm_g, ...
       '- iter =', inform.iter, ...
       '- status =', inform.status ) )

p.h_row = [ 1 2 3 ] ;
p.h_col = [ 1 2 1 ] ;

x0 = [ 1 1 1 ];
control.model = 4;
[x, inform ] = galahad_nls( p, x0, 'nls_r', 'nls_j_sparse', ...
                            'nls_h_sparse', control );

disp( sprintf( 'Nls: \n%s %13.6e %s %8.4e %s %5.0f %s %4.0f', ...
       ' - final f =', inform.obj, ...
       '- ||g|| =', inform.norm_g, ...
       '- iter =', inform.iter, ...
       '- status =', inform.status ) )

p.h_row = [ 1 3 2 ] ;
p.h_col = [ 1 1 2 ] ;

x0 = [ 1 1 1 ];
control.model = 6;
[x, inform ] = galahad_nls( p, x0, 'nls_r', 'nls_j_sparse', ...
                           'nls_h_sparse', 'nls_p_sparse', control );

disp( sprintf( 'Nls: \n%s %13.6e %s %8.4e %s %5.0f %s %4.0f', ...
       ' - final f =', inform.obj, ...
       '- ||g|| =', inform.norm_g, ...
       '- iter =', inform.iter, ...
       '- status =', inform.status ) )

% options

x0 = [ 4 3 2 ];
[ control ] = galahad_nls( 'initial' );
control.model = 3;
[x, inform ] = galahad_nls( p, x0, 'nls_r', 'nls_j_sparse', control );

%  solve with default values

x0 = [ 4 3 2 ];
[x, inform ] = galahad_nls( 'existing', p, x0, 'nls_r', 'nls_j_sparse', ...
                            control );

disp( sprintf( 'Nls: \n%s %13.6e %s %8.4e %s %5.0f %s %4.0f', ...
       ' - final f =', inform.obj, ...
       '- ||g|| =', inform.norm_g, ...
       '- iter =', inform.iter, ...
       '- status =', inform.status ) )

%  solve with direct solution of the subproblems

x0 = [ 4 3 2 ];
control.subproblem_direct = 1;
[x, inform ] = galahad_nls( 'existing', p, x0, 'nls_r', 'nls_j_sparse', ...
                            control );

disp( sprintf( 'Nls: \n%s %13.6e %s %8.4e %s %5.0f %s %4.0f', ...
       ' - final f =', inform.obj, ...
       '- ||g|| =', inform.norm_g, ...
       '- iter =', inform.iter, ...
       '- status =', inform.status ) )

galahad_nls( 'final' )
