name: Build and upload to PyPI

# Publish when a new GitHub version is tagged:
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_pypi:
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}

    steps:
      - id: check
        run: |
          VERSION="${GITHUB_REF_NAME#v}"

          if curl -fsSL https://pypi.org/pypi/galahad-optrove/json | \
             jq -e ".releases[\"$VERSION\"]" > /dev/null; then
            echo "Version $VERSION already exists on PyPI"
            echo "should_build=false" >> "$GITHUB_OUTPUT"
          else
            echo "Version $VERSION not found on PyPI"
            echo "should_build=true" >> "$GITHUB_OUTPUT"
          fi

  build_wheels:
    needs: check_pypi
    if: needs.check_pypi.outputs.should_build == 'true' || github.event_name == 'pull_request'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Note: builds on these are backward compatible
        os: [ubuntu-latest, macos-15-intel, macos-15, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set macOS deployment target
        if: runner.os == 'macOS'
        run: echo "MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | cut -d '.' -f 1-2)" >> $GITHUB_ENV

      - name: Set macOS OpenBLAS paths
        if: runner.os == 'macOS'
        run: |
          if [[ "${{matrix.os}}" == "macos-15" ]]; then
            echo PKG_CONFIG_PATH="/opt/homebrew/opt/openblas/lib/pkgconfig" >> $GITHUB_ENV
          fi
          if [[ "${{matrix.os}}" == "macos-15-intel" ]]; then
            echo PKG_CONFIG_PATH="/usr/local/opt/openblas/lib/pkgconfig" >> $GITHUB_ENV
          fi

      - name: Build wheels
        run: pipx run cibuildwheel==4.2.1
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
        env:
          # list of python versions and platforms to build on
          CIBW_BUILD: cp3{10,11,12,13,14}-manylinux_x86_64 cp3{10,11,12,13,14}-macosx_x86_64 cp3{10,11,12,13,14}-macosx_arm64 cp3{10,11,12,13,14}-win_amd64

          # set OpenMP variables on Linux and Windows
          CIBW_ENVIRONMENT: OMP_CANCELLATION=true OMP_PROC_BIND=true

          # build with gcc/gfortran on macOS and set OpenMP variables on macOS
          CIBW_ENVIRONMENT_MACOS: CC="gcc-14" CXX="g++-14" FC="gfortran-14" OMP_CANCELLATION=true OMP_PROC_BIND=true

          # build with OpenBLAS
          CIBW_BEFORE_ALL_LINUX: yum install -y openblas-devel
          CIBW_BEFORE_ALL_MACOS: brew install openblas

          # cibuildwheel doesn't yet ship a default repair command for Windows
          CIBW_BEFORE_BUILD_WINDOWS: pip install delvewheel
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --ignore-existing -w {dest_dir} {wheel}"

          # test built wheels
          CIBW_TEST_REQUIRES: numpy
          CIBW_TEST_COMMAND: |
            python {project}/src/arc/Python/test_arc.py
            python {project}/src/bgo/Python/test_bgo_quadratic.py
            python {project}/src/bgo/Python/test_bgo.py
            python {project}/src/blls/Python/test_blls.py
            python {project}/src/bllsb/Python/test_bllsb.py
            python {project}/src/bnls/Python/test_bnls.py
            python {project}/src/bqp/Python/test_bqp.py
            python {project}/src/bqpb/Python/test_bqpb.py
            python {project}/src/bsc/Python/test_bsc.py
            python {project}/src/clls/Python/test_clls.py
            python {project}/src/convert/Python/test_convert.py
            python {project}/src/cqp/Python/test_cqp.py
            python {project}/src/cro/Python/test_cro.py
            python {project}/src/dgo/Python/test_dgo_quadratic.py
            python {project}/src/dgo/Python/test_dgo.py
            python {project}/src/dps/Python/test_dps.py
            python {project}/src/dqp/Python/test_dqp.py
            python {project}/src/eqp/Python/test_eqp.py
            python {project}/src/fdc/Python/test_fdc.py
            python {project}/src/fit/Python/test_fit.py
            python {project}/src/glrt/Python/test_glrt.py
            python {project}/src/gls/Python/test_gls.py
            python {project}/src/gltr/Python/test_gltr.py
            python {project}/src/hash/Python/test_hash.py
            python {project}/src/ir/Python/test_ir.py
            python {project}/src/l2rt/Python/test_l2rt.py
            python {project}/src/lhs/Python/test_lhs.py
            python {project}/src/llsr/Python/test_llsr.py
            python {project}/src/llst/Python/test_llst.py
            python {project}/src/lms/Python/test_lms.py
            python {project}/src/lpa/Python/test_lpa.py
            python {project}/src/lpb/Python/test_lpb.py
            python {project}/src/lsqp/Python/test_lsqp.py
            python {project}/src/lsrt/Python/test_lsrt.py
            python {project}/src/lstr/Python/test_lstr.py
            python {project}/src/nls/Python/test_nls.py
            python {project}/src/nodend/Python/test_nodend.py
            python {project}/src/nrek/Python/test_nrek.py
            python {project}/src/presolve/Python/test_presolve.py
            python {project}/src/psls/Python/test_psls.py
            python {project}/src/qpa/Python/test_qpa.py
            python {project}/src/qpb/Python/test_qpb.py
            python {project}/src/roots/Python/test_roots.py
            python {project}/src/rpd/Python/test_rpd.py
            python {project}/src/rqs/Python/test_rqs.py
            python {project}/src/sbls/Python/test_sbls.py
            python {project}/src/scu/Python/test_scu.py
            python {project}/src/sec/Python/test_sec.py
            python {project}/src/sha/Python/test_sha.py
            python {project}/src/sils/Python/test_sils.py
            python {project}/src/slls/Python/test_slls.py
            python {project}/src/sllsb/Python/test_sllsb.py
            python {project}/src/sls/Python/test_sls.py
            python {project}/src/snls/Python/test_snls.py
            python {project}/src/ssls/Python/test_ssls.py
            python {project}/src/trb/Python/test_trb.py
            python {project}/src/trek/Python/test_trek.py
            python {project}/src/trs/Python/test_trs.py
            python {project}/src/tru/Python/test_tru.py
            python {project}/src/ugo/Python/test_ugo.py
            python {project}/src/uls/Python/test_uls.py
            python {project}/src/wcp/Python/test_wcp.py

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    needs: check_pypi
    if: needs.check_pypi.outputs.should_build == 'true'
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    needs: [check_pypi, build_wheels, build_sdist]
    if: needs.check_pypi.outputs.should_build == 'true' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
