name: Clang
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: aarch64-apple-darwin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Install Julia 1.7 for BinaryBuilder. Note that this is an old version of
      # Julia, but it is required for compatibility with BinaryBuilder.
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1.7"
          arch: x64
      # Set environment variables required by BinaryBuilder.
      - name: Set the environment variables
        run: |
          git fetch --tags
          echo "GALAHAD_RELEASE=$(git describe --tags $(git rev-list --tags --max-count=1) | sed 's/^v//')" >> $GITHUB_ENV
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "GALAHAD_COMMIT=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
            echo "GALAHAD_URL=${{ github.event.pull_request.head.repo.clone_url }}" >> $GITHUB_ENV
          else
            echo "GALAHAD_COMMIT=${{ github.sha }}" >> $GITHUB_ENV
            echo "GALAHAD_URL=https://github.com/${{ github.repository }}.git" >> $GITHUB_ENV
          fi
          echo "BINARYBUILDER_AUTOMATIC_APPLE=true" >> $GITHUB_ENV
      - name: Compile GALAHAD_jll
        run: |
          julia --color=yes -e 'using Pkg; Pkg.add("BinaryBuilder")'
          julia --color=yes .github/julia/build_tarballs_yggdrasil.jl aarch64-apple-darwin-libgfortran5 --verbose --deploy="local"
