name: Sanitizers
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sanitizers-linux-build:
    name: ${{ matrix.os }}/${{ matrix.compiler }}-v${{ matrix.version }}/Int${{ matrix.int }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        arch: ['x64']
        compiler: ['gcc']
        version: ['14']
        int: ['32', '64']
        sanitizers: ['true']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run common setup
        uses: ./.github/meson
        with:
          os: ${{ matrix.os }}
          compiler: ${{ matrix.compiler }}
          version: ${{ matrix.version }}
          int: ${{ matrix.int }}
          sanitizers: ${{ matrix.sanitizers }}
